### ISSUE TITLE
How install on LG WebOS 4?

### ISSUE THREAD

**Issue by JLFN** [jellyfin/jellyfin-webos#1]
Please post instructions how to install.

**Comment by anthonylavado** [comment]
Hi @JLFN :wave:
The app isn’t actually ready yet - it’s in a very early alpha stage, and not everything works properly. Until we are able to finish it and submit it to the LG App Store, I would just recommend using the Web Browser, or another app called “Screenplay”.

**Comment by EraYaN** [comment]
One of the best options on webOS 4.x is to use DLNA actually (Photos & Videos app). This will play the most files and have the best experience. The ipk posted on the releases page can only be installed while developer mode is active using the IDE of the CLI (ares etc).
