### ISSUE TITLE
Black screen on WebOS 5

### ISSUE THREAD

**Issue by erpalma** [jellyfin/jellyfin-webos#100]
Hi, I'm testing the latest JF on WebOS 5 using dev mode. I've set-up the server address (online server, over https). I can clearly see lots of successful GETs on the server (among which web/index.html, Users/xxxx, etc.) but the TV screen remains black. No errors whatsoever. Clearly from the browser and the Android App everything works fine. What can I do to debug this behavior?

**Comment by lexcorp** [comment]
@erpalma What version of firmware webos 5 do you have?

I'm using Firmware: 05.25.35 and Jellyfin WebOS works fine...

**Comment by anthonylavado** [comment]
Possibly a duplicate of #88?

**Comment by erpalma** [comment]
Actually I don't have any custom theme and no CSP-related settings in nginx. Still, I will try to alter some settings in the reverse proxy and report back.

@lexcorp FW 05.25.35.

**Comment by erpalma** [comment]
Ok I guess that it is better not to add any header (I left only Strict-Transport-Security) in nginx when proxying JF. Working fine now.
