### ISSUE TITLE
SUGGESTION Add OnScreen Virtual Keyboard to Jellyfin WebOS

### ISSUE THREAD

**Issue by lexcorp** [jellyfin/jellyfin-webos#103]
I suggest adding a virtual on-screen keyboard for Jellyfin WebOS, to make it easier for users to enter text during app setup or when searching for a movie. It is complicated to enter letter by letter with the control.

https://webostv.developer.lge.com/design/webos-tv-system-ui/virtual-keyboard/

https://github.com/hodgef/simple-keyboard

https://github.com/furcan/KioskBoard

https://github.com/xlab/matchbox-keyboard

![68747470733a2f2f692e696d6775722e636f6d2f507270626449752e706e67](https://user-images.githubusercontent.com/5751288/182038770-89637350-0c80-43a2-bc18-75c9289b0ac8.png)

![Design_webOSTV60_VirtualKeyboard](https://user-images.githubusercontent.com/5751288/182038842-da7bc8d8-b8d7-4de1-84a7-3777f36ebba3.png)

**Comment by lexcorp** [comment]
webOS TV provides the system keyboard which is automatically displayed on the webOS TV screen if you let your cursor in the text window. The system keyboard is called the virtual keyboard for webOS TV. The virtual keyboard is the primary text input method for the webOSTV app, and you can customize it as the following types.

https://github.com/webOS-TV-app-samples/VirtualKeyboard

https://webostv.developer.lge.com/design/webos-tv-system-ui/virtual-keyboard/

**Comment by anthonylavado** [comment]
I'm sorry, what's the request here?

**Comment by lexcorp** [comment]
Sorry Anthony, this feature is native to LG Web OS and I understand that character input depends on the remote control or keyboard connected to the display.
