### ISSUE TITLE
TrueHD support detection is bad

### ISSUE THREAD

**Issue by kvaster** [jellyfin/jellyfin-webos#111]
TrueHD support is detected by checking 'deviceInfo.dolbyAtmos' but this flag does not indicate TrueHD support in applications. I have LG OLED C2 and it has support for Dolby TrueHD only in passthrough mode (from HDMI devices). It can't play TrueHD sound from applications.

**Comment by Gerben321** [comment]
Same issue. Same goes for regular Atmos.

**Comment by Otako77** [comment]
https://github.com/jellyfin/jellyfin-webos/issues/118#issuecomment-1367695609
