### ISSUE TITLE
LG Magic Remote Doesn't Have Forward & Back Buttons

### ISSUE THREAD

**Issue by patel8786** [jellyfin/jellyfin-webos#125]
Pressing the right or left button doesn't skip forward/backward. I've read that the rewind/fast forward buttons need to be used for skipping. The LG Magic Remotes don't have those buttons.

[https://www.lg.com/us/magic-remote](url)

It would be great to allow users to choose to rather use the left/right buttons for skipping.

**Comment by burrodesancho** [comment]
After pressing left or right button, press up button to focus on slider. Now you can use left/right button for rewind/fast forward.

Personally, I prefer immediate rewind/fast forward on left/right button press.
Same thing with play/pause on single OK button press - currently two button presses are needed...

**Comment by dmitrylyzo** [comment]
The main problem is how to combine this with navigation.

Possible solution:
Change the reaction when the OSD is hidden.
1. Pressing the left/right button displays the OSD, sets the focus on the progress bar and starts dragging.
2. Pressing OK displays the  OSD, sets the focus on the Pause, and pauses the video.

Once the OSD menu appears, the buttons function as usual.

**Comment by DrConflict** [comment]
Has there been any progress made on this issue? Or a potential beta version people can test?

**Comment by maildopereira** [comment]
I Installed version  10.8.10, and I have this problem.
Pressing the right or left button doesn't skip forward/backward, with the Magic Remote on my WebOS 5.

It works fine with a keyboard on my PC via HTTP to the server ( http://_my.server.internal.ip_:8096/web/index.html ).

Is there a workaround or a fix comming soon?
