### ISSUE TITLE
Jellyfin for WebOS 4

### ISSUE THREAD

**Issue by caeci11ius** [jellyfin/jellyfin-webos#130]
Now that we have Jellyfin for WebOS 5 (thankyou for all your efforts @anthonylavado), could we perhaps track availability for WebOS 4 (which I think covers model -8 and -9 TVs based on [this](https://webostv.developer.lge.com/develop/specifications/web-api-and-web-engine) )?

Possibly also for WebOS 3. I can see there's a bug blocking WebOS 1 and 2 (which may be naturally reducing in number anyway due to age, not to mention coming off a lower base given the high prices for OLEDs when they were released).

No dramas if you want to lock the thread and just report back now and then like last time - it actually was a great way to get updates without having to check back manually from time to time - folks can just subscribe to this thread. Also, no expectations of anything happening quickly, I saw all the comments around LGs submission timeframes. I just want to be able to jump on it as soon as it's ready (and migrate from...the inferior competition...once and for all!).

**Comment by mwessman** [comment]
I'm also waiting to hear more about WebOS 4. I'm currently considering whether I should just buy a Chromecast so I can use Jellyfin with my TV instead of Plex.
An ETA for WebOS 4 would be cool so I know whether I should just buy a chromecast now or keep waiting.

**Comment by gerardo-junior** [comment]
+1

**Comment by artogahr** [comment]
FWIW, I'm using the Jellyfin app on my WebOS 4 TV (43UK6470), by sideloading Homebrew channel using Dev mode. I'm using a IFTTT script that periodically makes an API request to keep the Dev mode timer from reaching 0.

**Comment by anthonylavado** [comment]
https://github.com/jellyfin/jellyfin-webos/issues/138#issuecomment-1584814969
