### ISSUE TITLE
Choice to prefer DV over HDR compatible

### ISSUE THREAD

**Issue by Kimi-Arthur** [jellyfin/jellyfin-webos#140]
Hi there,

It's awesome Jellyfin is finally launched for Web OS 5. And more awesomely, it solved the problem of playing back DV (only) videos.

One minor problem (which I'm not sure whether it's LG specific or not) is that if the video track is DV as well as HDR compatible, Jellyfin will only play the compatible track. That's OK, but if the DV version is preferred (by default or by option), that will be even better!

If such a test video is needed, I can produce a short one, but otherwise, a lot of the Bluray rips are of that format (DV + HDR compatible).

The mediainfo lines look like:

```
HDR format: Dolby Vision, Version 1.0, dvhe.07.06, BL+EL+RPU, Blu-ray compatible / SMPTE ST 2086, HDR10 compatible
```

**Comment by mtosic** [comment]
LG cannot play DV in mkv container, you need mp4 or ts container to watch DV.
That's why it fallback to HDR (if mkv is profile 8). With profile 5 mkv you don't even get fallback to HDR base layer, instead you get green/purple tones.

**Comment by Kimi-Arthur** [comment]
I see. I repacked the mkv DV to mp4 and it seems to show DV properly.

Is that what you mean? Thanks for your clarification!

**Comment by Kimi-Arthur** [comment]
Sorry, one more related question. Is there a way to demux such MKV files on the fly to support such streams? Demux should be somewhat lightweight?

Thanks!

**Comment by mtosic** [comment]
I'm not sure if Plex or Jellyfin support remuxing on the fly (I'm not using any of media servers).
I think the easiest way is batch script with ffmpeg (if you used that for converting mkv to mp4) after video is converted to mkv (or any other process you are using).

There is a nice script (for linux though) for converting mkv to mp4.
https://github.com/gacopl/dvmkv2mp4

**Comment by Kimi-Arthur** [comment]
I guess it would be sufficient to just mark MKV as unsupported (with an option of course), but I'm not sure.

Here is a reference from Jellyfin's website: https://jellyfin.org/docs/general/clients/codec-support/#container-compatibility

From its wording, it's costing only a tiny bit for this.

**Comment by mtosic** [comment]
Interesting, I don't know what are they using for remuxing, but ffmpeg remux is not instantaneous, because I've used ffmpeg option from https://github.com/jellyfin/jellyfin-webos/issues/109 and it takes some time.
