### ISSUE TITLE
WebOS player controls not intuitive to use

### ISSUE THREAD

**Issue by DrConflict** [jellyfin/jellyfin-webos#145]
Basic actions like scrolling through content, or skipping back and forward require multiple button presses when it could be more refined and logical. For instance, if I want to skip forward 30 seconds, I have to press UP twice (first to show the player UI, second to select the position marker), then press RIGHT to skip forward. I think It would make more sense to just press LEFT and RIGHT while watching to skip back and forward instantly.

Imo, the way both Plex and Emby do this is ideal, and should probably be used as an example to control the JF player as well. People who make the switch from those platforms would feel right at home instantly with the controls. Currently the WebOS controls feel clunky and strange to use.

**Comment by dmitrylyzo** [comment]
dup #125

**Comment by DrConflict** [comment]
> dup #125

Woops, my bad! Apologies.
