### ISSUE TITLE
Cannot install ipk

### ISSUE THREAD

**Issue by liontiger23** [jellyfin/jellyfin-webos#147]
Today my TV decided again to reset developer mode and delete jellyfin app (I'm using webOS 4) and updated developer mode app.

I went through the whole re-registering TV in `ares` app and now when I try to install ipk it fails with following:
```
$ ares-device-info -d tv
modelName : 55NANO866NA
sdkVersion : 5.4.2
firmwareVersion : 04.40.70
boardType : K6HP_DVB_CS
otaId : HE_DTV_W20H_AFADABAA
$ ares-install -d tv org.jellyfin.webos_*.ipk
ares-install ERR! [ssh exec failure]: Command '/bin/rm -rf /media/developer/temp && /bin/mkdir -p /media/developer/temp' exited with code=1 (signal: undefined)
```

When I ssh to TV there is a `/media/developer/temp` directory owned by root, so I can't recreate this command manually.

I understand that it is probably more an issue with developer mode and webOS, but maybe someone can help me figure it out?

**Comment by vtol79** [comment]
I had the same issue about a week ago even though updates are disabled on my TV.

You need to update the webOS_TV_CLI version to 1.12.4 in order to install the app again!
https://webostv.developer.lge.com/develop/tools/cli-installation

Br,

**Comment by liontiger23** [comment]
Indeed, it works.

Thank you very much!

**Comment by Doomsdayrs** [comment]
this should not be closed, the issue is still present

**Comment by sgsunder** [comment]
I'll add more info on how to workaround this issue:

1) Download the Linux x64 tarball of the CLI tools from the link provided above: https://webostv.developer.lge.com/develop/tools/cli-installation
2) Extract the contents of the tarball to the root of this repo. There should be a new directory named `CLI`
3) Follow the Docker instructions as written in the readme, but modify each command: where it says `./dev.sh ares-<whatever> ...`, instead use `./dev.sh ./CLI/bin/ares-<whatever> ...`
