### ISSUE TITLE
Add the option to enable/disable: "Play next Episode Automatically"

### ISSUE THREAD

**Issue by Kivylius** [jellyfin/jellyfin-webos#151]
This seems to work on all devices, other then LG (Web and App). Why is there a lack of information about this? And why is it missing option? 

This was posted half year back as an issue on Reddit:

https://www.reddit.com/r/jellyfin/comments/yx445j/why_is_there_no_play_next_episode_automatically/

This quite frustration for me as I fall asleep and episodes play all night. Please add this option?

Jellyfin: 10.8.9

**Comment by dmitrylyzo** [comment]
> And why is it missing option?

Inherited from Emby, and no one knows why it was done.

https://github.com/jellyfin/jellyfin-web/blob/63c25b11fa0bda9c940e914b66ed75d0c40e34bb/src/components/playbackSettings/playbackSettings.js#L141-L144

There were other settings disabled on TV in a similar way: theme background and theme song. But this, at least, can be explained by the low performance of the hardware on TV.
