### ISSUE TITLE
LG TV doesn't load Jellyfin interface after update to 10.8.10

### ISSUE THREAD

**Issue by etu** [jellyfin/jellyfin-webos#154]
Heya, I'm really not sure where to report this.

Here goes!

My LG TV runs WebOS 5 with the latest (I guess, I checked in the store and there was no obvious update) installed app from the LG Content Store.

It's been working perfectly with Jellyfin 10.8.9, today I did a system update and got 10.8.10 and now the interface doesn't load anymore. It just shows the Jellyfin logo and text and then nothing.

It shows up in my nginx log like it tries to do a normal load of the page. It works on my android app and in Firefox... so I'm not sure what's going on.

I've rolled my system back to run 10.8.9 and it works fine then...

**Comment by etu** [comment]
After further investigation.... including downgrading I have concluded that it's not due to the jellyfin version and rather something else in my system. I'm currently git bisecting my server. I'll comment back if I find something in case someone else finds this thread.

**Comment by jsimonetti** [comment]
I am experiencing identical issues as you. LG tv app hangs at logo after login. Other clients (android/ios/web) work fine and as expected.
Please do comment back if you find something.

**Comment by etu** [comment]
So I have bisected it down to be this https://github.com/NixOS/nixpkgs/commit/36034fbc517692ee203cac218b1dc0658ebfd7cc  commit that broke it for me, when I first made my override I *only* did an override on the Jellyfin package, not the jellyfin-web package.

So keeping 10.8.10 of jellyfin and switching back to jellyfin-web to 10.8.9 even on the latest unstable of all other packages on the system makes the interface load again.

I'm going to continue bisecting this, just this time, it's going to be in the jellyfin-web project :slightly_smiling_face:

**Comment by etu** [comment]
Here's my bisect log:
```
git bisect start
# status: waiting for both good and bad commits
# good: [72c66e91ed7f7e3608c4e6a520b6ee6029e5ef19] Bump version to 10.8.9
git bisect good 72c66e91ed7f7e3608c4e6a520b6ee6029e5ef19
# status: waiting for bad commit, 1 good commit known
# bad: [55714d5341d6bbfdb4d8b0b4c9b6955d4db14f34] Bump version to 10.8.10
git bisect bad 55714d5341d6bbfdb4d8b0b4c9b6955d4db14f34
# bad: [7e99e3ec515d9a461358b5053da0c78a9f452e8d] Merge pull request #4330 from dmitrylyzo/fix-navigation-input
git bisect bad 7e99e3ec515d9a461358b5053da0c78a9f452e8d
# good: [e580f0c8695f4e28873b3ecc494178b0718cbb61] Fix navigation for some types of INPUT
git bisect good e580f0c8695f4e28873b3ecc494178b0718cbb61
# bad: [8f75a426696b26204d44a46143c25bf48f936639] Merge pull request #4356 from dmitrylyzo/babel-libass
git bisect bad 8f75a426696b26204d44a46143c25bf48f936639
# bad: [38aebf4e42cb1d1df3b6882ab31770b3961faa70] Babelify @jellyfin/libass-wasm
git bisect bad 38aebf4e42cb1d1df3b6882ab31770b3961faa70
# bad: [62d0354fe09df348c665c813dffb273de4542929] Simplify adding modules to babel-loader
git bisect bad 62d0354fe09df348c665c813dffb273de4542929
# first bad commit: [62d0354fe09df348c665c813dffb273de4542929] Simplify adding modules to babel-loader
```

So to me it seems like https://github.com/jellyfin/jellyfin-web/commit/62d0354fe09df348c665c813dffb273de4542929 caused some kind of regression for the LG TV browser.

**Comment by jsimonetti** [comment]
@etu I am interested in how you did the override for jellyfin-web, (Coincidentally i also run nixos) so I can keep the wife happy 😃

**Comment by etu** [comment]
@jsimonetti Here you go
```nix
{ ... }: 
{
  services.jellyfin.package = pkgs.jellyfin.override {
    jellyfin-web = pkgs.jellyfin-web.overrideAttrs (oa: rec {
      version = "10.8.9";
      src = pkgs.fetchFromGitHub {
        owner = "jellyfin";
        repo = "jellyfin-web";
        rev = "v${version}";
        sha256 = "hHZ8HVf8fidd5VPs06kB3/BHBHFxoV3fVObBesqfRJo=";
      };
    });
  };
}
```

**Comment by etu** [comment]
I'll also re-open this issue since it *may* be client related... I'm just not feeling confident about how to investigate this further.

**Comment by etu** [comment]
@jsimonetti And now this broke due to some refactoring in the jellyfin-web on NixOS. So I just pinned it instead. https://github.com/etu/nixconfig/commit/9d113227cc71147670656e20c9e7ab6fd8e0b511

**Comment by jsimonetti** [comment]
> @jsimonetti And now this broke due to some refactoring in the jellyfin-web on NixOS. So I just pinned it instead. [etu/nixconfig@9d11322](https://github.com/etu/nixconfig/commit/9d113227cc71147670656e20c9e7ab6fd8e0b511)

Thanks for the headsup! Hopefuly this can be resolved quickly.

**Comment by etu** [comment]
Oh, interesting, I just tried updating to 10.8.10 again using that update of node and it seems to work on my LG TV. Thanks for pointing that one out :slightly_smiling_face:
