### ISSUE TITLE
Weird issue LG TV error -27

### ISSUE THREAD

**Issue by SEPPDROID** [jellyfin/jellyfin-webos#157]
After buying a brand new LG tv (OLED65G36LA) we immediately installed jellyfin to enjoy all off our movies. However when trying to connect to the server we get an extremely odd error:

(Translated from dutch)
Application error, the TV might be overheating. 
code -27

I first thought that we might left some plastic over one of the vent holes but that was not the case. The TV is as cool as ice. Other streaming apps and movies can run for hours.  
I noticed in the logs that the connection never reaches the server. 

I will add media to this issue soon because im writing this at the top of my head. It could be possible we are doing something wrong.

**Comment by dmitrylyzo** [comment]
Usually "error -27" is a network problem.
https://github.com/jellyfin/jellyfin-webos/issues/60

But "overheating" 🤨

How you connect to the server?

**Comment by SEPPDROID** [comment]
That’s what puzzled me… the only options we got was to restart application or quit the application. And restarting it with “remember server” would loop the error. 

was trying to connect over https:// my.domain.com

i will make a video tomorrow for clarification, as it is an error i have never seen before. 

just maybe with my luck it will resolve itself overnight 😅

**Comment by SEPPDROID** [comment]
Thank you for linking the other issue

https://github.com/jellyfin/jellyfin-webos/issues/60#issuecomment-1397538430

here i read about a generic temperature issue wich is probably (badly) translated to dutch coming up with an overheating error.

i will take a look at the x cross origin settings in the config to see if that resolves it.

**Comment by SEPPDROID** [comment]
-27 is indeed a network error, error description made it confusing. I ran an old config and never noticed that the X-Frame-Options header caused a connection issue on the webos client. 

Error -27 disappeared after commenting out the X-Frame-Options. Which is fine for now

**Comment by hdswiss** [comment]
> -27 is indeed a network error, error description made it confusing. I ran an old config and never noticed that the X-Frame-Options header caused a connection issue on the webos client.
> 
> Error -27 disappeared after commenting out the X-Frame-Options. Which is fine for now

Can you please post the configuration here? I have the same problem.

**Comment by hdswiss** [comment]
> -27 is indeed a network error, error description made it confusing. I ran an old config and never noticed that the X-Frame-Options header caused a connection issue on the webos client.
> 
> Error -27 disappeared after commenting out the X-Frame-Options. Which is fine for now

Can you please post the configuration here? I have the same problem.

**Comment by NoSubstitute** [comment]
Another year later, and it's still an issue, as the WebOS app hasn't been updated.

Anyway, it can be fixed by adjusting the nginx config. This issue discusses it, and the sample conf has it fixed.
https://github.com/linuxserver/reverse-proxy-confs/pull/731
https://github.com/linuxserver/reverse-proxy-confs/blob/master/jellyfin.subdomain.conf.sample
