### ISSUE TITLE
Subtitles are too bright when playing HDR content.

### ISSUE THREAD

**Issue by DamianPereira** [jellyfin/jellyfin-webos#158]
This is specially noticeable on dark scenes on my LG C2, the subtitle literally lights up the entire room compared to the dark scene. An option to change subtitle color would allow users to select a gray color for subs instead of white, which might solve the issue. Another alternative might be just using a default gray/transparent subtitle for hdr content.

Example of how this looks, you can even see that the excessive brightness washes out the colors a bit:
![20230603_015046](https://github.com/jellyfin/jellyfin-webos/assets/17646954/89ac5fc0-cede-4e67-8d09-22bcab0baca2)

Same scene on netflix player (subtitle is still white, but not as bright for some reason)
![20230603_015703](https://github.com/jellyfin/jellyfin-webos/assets/17646954/82fed4df-1caf-4b80-860b-311cd9365748)

**Comment by DamianPereira** [comment]
UI Icons also display the same issue, they are much brighter than needed.

**Comment by DamianPereira** [comment]
It seems like this will be fixed by jellyfin-web 10.9 according to this: https://github.com/jellyfin/jellyfin-web/issues/3327. So closing this issue since it will eventually be solved when that releases and this wrapper is updated.

**Comment by dadodasyra** [comment]
Seems like it's still a thing on jellyfin android app
