### ISSUE TITLE
Display mode setting missing - DPI setting on 77" is to large

### ISSUE THREAD

**Issue by wacko37** [jellyfin/jellyfin-webos#160]
Hi team, firstly thanks for all that you do! much appreciated indeed!

So i have just setup Jellyfin on my new 77" G3..... very impressed to say the least. Only problem I'm having is that everything is to over sized, leaving everything feeling very squashed. 

Normally there is a Display mode setting with jellyfin that allowing you to change between Auto, Desktop, Mobile or TV, sadly this is not present.

Is there anyway I can change the DPI setting of the app?

**Comment by anthonylavado** [comment]
I think we default to TV when the resolution is detected. I forget the exact spot this happens.

**Comment by wacko37** [comment]
> 

Thanks Anthony for the reply and your efforts in making such things a possibility! 

Is there any way I can edit the app to test "Desktop" Display mode?

**Comment by wacko37** [comment]
This was caused by a custom CSS, altough it would be good to have the option to select different display modes.
