### ISSUE TITLE
Impossible to install outside USA

### ISSUE THREAD

**Issue by pippo73** [jellyfin/jellyfin-webos#171]
Hello, 
Is there a way to install this app to a oled55c8pla tv that is set to the italian market. Apparently the app is only for USA market :-(

**Comment by Dycelll** [comment]
I’m in Europe and I don’t think the app is geo limited
Check your webos version, you need at least version 5. See other questions here, how to verify your version. 

I think an update for older Webos versions is pending…

**Comment by pippo73** [comment]
> I’m in Europe and I don’t think the app is geo limited Check your webos version, you need at least version 5. See other questions here, how to verify your version.
> 
> I think an update for older Webos versions is pending…

Could you tell me in which country you are, because nor on the tv nor on the website is possibile to find the app.

on my tv I have 05.50.15 version installed

**Comment by hmonteiro** [comment]
That version is the firmware version. LG make it confusing, you need to check the webos version deep in the menu system. I made the same mistake, my TV is also running a 5.* firmware, but the webos version is 4.* Looking at the age of your TV, I suspect you are also on 4.* so you'll have to wait until the app is released officially for that version.

**Comment by pippo73** [comment]
Ok, let's do in a different way.
Here you can see firmware and webos versions 😉

**Comment by Dycelll** [comment]
Well, best thing is to wait for the next update to go though:
https://github.com/jellyfin/jellyfin-webos/issues/169
if you can’t wait that long, side loading is an option..

**Comment by anthonylavado** [comment]
Since this is technically a TV version issue, closing as "can't fix". As the other commenter mentioned, you can follow the update ticket.

**Comment by cremor** [comment]
> Here you can see firmware and webos versions

@pippo73 That is not the WebOS version number. I don't know what Netflix shows there, but you have a C8 (2018 model), so you have WebOS version 4.x. If you want to find it in detail, you have to go to the TV's system settings. On the page where you can search for firmware updates there is another sub-page where the WebOS version is shown.
The Jellyfin version on the LG content store is only for WebOS 5+ currently.

**Comment by pippo73** [comment]
> > Here you can see firmware and webos versions
> 
> @pippo73 That is not the WebOS version number. I don't know what Netflix shows there, but you have a C8 (2018 model), so you have WebOS version 4.x. If you want to find it in detail, you have to go to the TV's system settings. On the page where you can search for firmware updates there is another sub-page where the WebOS version is shown. The Jellyfin version on the LG content store is only for WebOS 5+ currently.

Sorry but on the page there is only the firmware version or maybe you could show me a Pic or write a more specific pls.
Tnx

**Comment by cremor** [comment]
Open the menu item "TV information" on that settings page: https://external-preview.redd.it/KrX0h4RAZFaQQEzusvNPIefJ5bIqYLHTi_0RB0Sz1Tc.jpg?width=640&crop=smart&auto=webp&s=29c6c3cedd252736db345c753f366c5860ddbeda
There you'll see something like this: https://preview.redd.it/v9lmv7addp241.jpg?width=640&crop=smart&auto=webp&s=de448dc4879c22ec3fd3f5a648cd54a56d4337bc

**Comment by pippo73** [comment]
Damn... :-( You are right ! I thoug I've searched all the menus but It seems I've missed this one :''''''-(
