### ISSUE TITLE
Setting audio track/subtitle track based on previous item not working correctly

### ISSUE THREAD

**Issue by admoore0** [jellyfin/jellyfin-webos#175]
More specifically, the UI will show the right audio/subtitle track selected, but the actual encoded audio/subtitle will be incorrect. I have subtitle burn-in set to "All".

**Comment by zarlin** [comment]
I'm also encountering this issue, in my case with subtitle burnin set to Auto. It feels like it just uses the default audio/subtitle tracks, but the UI does not match this. Fully restarting the episode will play with the correct settings.

**Comment by dmitrylyzo** [comment]
Should be fixed in https://github.com/jellyfin/jellyfin-web/pull/6112
