### ISSUE TITLE
webOS app on the LG app store is outdated, no color for subtitles

### ISSUE THREAD

**Issue by msimic** [jellyfin/jellyfin-webos#182]
I am unable to watch HDR movies on Jellyfin webOS due to the subtitles being too bright and distracting when HDR is enabled.
Burning in subtitles and configuring them on the server does not work either, since this forces transcoding, which disables HDR.

The feature to set subtitle color and other features has been added to jellyfin-web.

This is a commit that is needed: https://github.com/jellyfin/jellyfin-web/commit/25e4d378435adb0f22739712b5cde85f0066d795

Since the webOS client is just a wrapper around it, @anthonylavado  can you please build and publish a newer version of the webOS app to the LG app store?

**Comment by dmitrylyzo** [comment]
> Since the webOS client is just a wrapper around it, can you please build and publish a newer version of the webOS app to the LG app store?

It isn't bundled - the app uses webui directly from the server.
You will have to wait for Jellyfin 10.9 release.
Or, if you are willing to take the risk, use the unstable version (backing up the current server first, as it's not reversible).
