### ISSUE TITLE
Buffering?

### ISSUE THREAD

**Issue by misterbit-pro** [jellyfin/jellyfin-webos#19]
Hello WebOS Dev-Team,

is buffering active in this App, because when I want to watch high bitrate DV MP4 Remuxes it lags, it needs about 120Mbit/s, but I read on multitiple formus that LG TVs have problems with such high speeds due the the Ethernet Port is not Gigabit (only 100Mbit) and Wireless Connection is not stable enough. So my question is: Can buffering be implemeted in dzch way, so if there are such speeds needed, that the App tries to load at start as much as possibles and videos can then be played without lag?

**Comment by WilcoVertegaal** [comment]
Not sure if that's feasible ... In your case, where the required bitrate is 20% higher than what's available, it would mean that one sixth of the entire movie would need to be buffered for uninterrupted playback. For a 2 hour movie, that would be 20 minutes of buffered video. At 120Mb/s, that would be 20 * 60 * 120Mb = 144 000 Mb, or 17.5GB.

Maybe better to just compress your remuxes?

**Comment by EraYaN** [comment]
Your best option IS in fact WiFi, 5 GHz to be exact. Most higher-end LG TVs will sustain about 300 megabits per second with a good WiFi access point. though you might need to force a 5GHz only SSID, since LG seems to prefer 2.4GHz if available on the same SSID. I have a UniFi nanoHD at about 10 meters from the TV, and it will stream UHD bluray remuxes happily and quickly.

**Comment by besendorf** [comment]
You can also attach a Gigabit NIC via USB. Some people have reported that it worked for them

**Comment by misterbit-pro** [comment]
Currently I use a 5GHz Wifi connection and my speed is about 250Mbps and this shouldn't be a problem, but the limit is 120Mbps so its not really working at some scenes due to such ah high bitrate has to be streamed. And if I choose the Auto option its trancodes to 1080p. I don't know why but ok. So the limitation is at the jellyfins side I think. When I want to stream non Dolby Vision Content I use my SHIELD TV with Kodi  and the jellyfin addon and there the limitation goes up to 1000Mps and it plays without any problem. The thing is I can not stream Dual Layer Dolby Vision files there. Normal HDR yes and this works like I said with any problem.

**Comment by misterbit-pro** [comment]
Edit: With the jellyfin 10.5.5 Update, I can use auto without transcoding but the the lagginess persists

**Comment by EraYaN** [comment]
What model TV do you have? The SoCs in the different lines are not create equal. My C8 never has had a problem performance wise.

**Comment by misterbit-pro** [comment]
I have ah B8

**Comment by misterbit-pro** [comment]
It sad because no other client can stream dual layer DV. And I like the idea that it is always backwards compatible with HDR.

**Comment by WilcoVertegaal** [comment]
What are you streaming it from?

**Comment by misterbit-pro** [comment]
I'm using jellyfin 10.5.5 and the web os app I compiled myself or what are you referring to?

**Comment by WilcoVertegaal** [comment]
> @WilcoVertegaal I'm using jellyfin 10.5.5 and the web os app I compiled myself or what are you referring to?

@misterbit-pro I'm referring to the hardware that you are running the Jellyfin server on.

**Comment by misterbit-pro** [comment]
> > @WilcoVertegaal I'm using jellyfin 10.5.5 and the web os app I compiled myself or what are you referring to?
> 
> @misterbit-pro I'm referring to the hardware that you are running the Jellyfin server on.

i7-7700, jellyfin on m.2 ssd, all the movies on hdd

**Comment by JustAMan** [comment]
To answer original question, _how_ the TV plays the content (how much it buffers, etc.) cannot be controlled from the app. We can only give it a URL with media to play from, and it would go on on its own. So it seems there's nothing we could do on our end here.

Also I can imagine that network might not be to blame, but rather slow decode of high-bitrate content on the TV itself. Try playing the movie you want from a USB3 device, it could show the difference (then network is to blame) or no difference (then the TV itself is to weak to decode the stream in time).

**Comment by misterbit-pro** [comment]
> To answer original question, _how_ the TV plays the content (how much it buffers, etc.) cannot be controlled from the app. We can only give it a URL with media to play from, and it would go on on its own. So it seems there's nothing we could do on our end here.
> 
> Also I can imagine that network might not be to blame, but rather slow decode of high-bitrate content on the TV itself. Try playing the movie you want from a USB3 device, it could show the difference (then network is to blame) or no difference (then the TV itself is to weak to decode the stream in time).

Ok thanks i will try that with the usb stick. But it takes some time, because it will take a while to download the movie. But thanks for now

**Comment by misterbit-pro** [comment]
But beside testing this later. Has anyone else tried to stream MP4 DV Remuxes with the webOS App? It would be great to know if anyone else got it working or not.

**Comment by misterbit-pro** [comment]
I have now found time to watch a dv mp4 movie and from the usb stick it works without any problems. I don't know why it doesn't work with jellyfin. I can only imagine that the 120Mpbs limit isthe bottleneck here. I will also try if it work better wehen I stream the move from the m.2 ssd instead of using the hdd.

**Comment by EraYaN** [comment]
Well the B8 has 100MBit Ethernet, so if you are not using fast WiFi that will be your bottleneck.

**Comment by misterbit-pro** [comment]
> Well the B8 has 100MBit Ethernet, so if you are not using fast WiFi that will be your bottleneck.

I am using wifi. But jellyfin has a software side limit of 120Mbps. This must be the problem in my opinion. This only happens if the bitrate is really high, only at some scenes. Because i downloaded the Dolby Vision Demo Pack and some trailer work and others don't. Too bad, but i already added a feature request to the fider platform to suppoert higher qualities than 120Mbps. I think this issue can't be fixed with buffering. So the issue can be closed.

**Comment by EraYaN** [comment]
> 
> 
> > Well the B8 has 100MBit Ethernet, so if you are not using fast WiFi that will be your bottleneck.
> 
> I am using wifi. But jellyfin has a software side limit of 120Mbps. This must be the problem in my opinion. This only happens if the bitrate is really high, only at some scenes. Because i downloaded the Dolby Vision Demo Pack and some trailer work and others don't. Too bad, but i already added a feature request to the fider platform to support higher qualities than 120Mbps. I think this issue can't be fixed with buffering. So the issue can be closed.

This has nothing to do with the transcoding limit? I stream UHD Bluray remuxes quite successfully, but the TV needs to be on a 5Ghz WiFi network that will do the appropriate speed. I have a Ubiquiti nanoHD and get about 300 Mbps on the TV. You can use fast.com in the webbrowser for example to easily test the speed to the internet (given that your home internet is fast enough to out pace your WiFi link).

**Comment by misterbit-pro** [comment]
> > 
> > 
> > > Well the B8 has 100MBit Ethernet, so if you are not using fast WiFi that will be your bottleneck.
> > 
> > I am using wifi. But jellyfin has a software side limit of 120Mbps. This must be the problem in my opinion. This only happens if the bitrate is really high, only at some scenes. Because i downloaded the Dolby Vision Demo Pack and some trailer work and others don't. Too bad, but i already added a feature request to the fider platform to support higher qualities than 120Mbps. I think this issue can't be fixed with buffering. So the issue can be closed.
> 
> This has nothing to do with the transcoding limit? I stream UHD Bluray remuxes quite successfully, but the TV needs to be on a 5Ghz WiFi network that will do the appropriate speed. I have a Ubiquiti nanoHD and get about 300 Mbps on the TV. You can use fast.com in the webbrowser for example to easily test the speed to the internet (given that your home internet is fast enough to out pace your WiFi link).

I have a Ubiquiti Amplifi Mesh System and it works well with every device I can say. Because I always stream 4K HDR BluRay Remuxes on my SHIELD with Kodi snd the jellyfin plugin. Only when I want to play 4K Dolby Vision Dual Layer MP4 Remuxes on my B8 i have the Problem that it begins to load after some time. I have to say I will update my network devices to UniFi in the near future, but it should work with tge Amplifi devices to. And I have the B8 directly connected to the Main Router do no Mesh Point with a 5GHz only conntection. So yeah i think theres any problem on the network side. Like I said I have to try moving my DV movies to the ssd and try again, but I also don't think this can be the bottleneck because the HDD has 250Mbit Read speeds. So yeah i have to investigate in this whole thing further when my time allows it. But for now my only working option is HDR10 on my SHIELD and no DV, but that's ok.

**Comment by besendorf** [comment]
> > > Well the B8 has 100MBit Ethernet, so if you are not using fast WiFi that will be your bottleneck.
> > 
> > 
> > I am using wifi. But jellyfin has a software side limit of 120Mbps. This must be the problem in my opinion. This only happens if the bitrate is really high, only at some scenes. Because i downloaded the Dolby Vision Demo Pack and some trailer work and others don't. Too bad, but i already added a feature request to the fider platform to support higher qualities than 120Mbps. I think this issue can't be fixed with buffering. So the issue can be closed.
> 
> This has nothing to do with the transcoding limit? I stream UHD Bluray remuxes quite successfully, but the TV needs to be on a 5Ghz WiFi network that will do the appropriate speed. I have a Ubiquiti nanoHD and get about 300 Mbps on the TV. You can use fast.com in the webbrowser for example to easily test the speed to the internet (given that your home internet is fast enough to out pace your WiFi link).

You can also run [librespeed](https://github.com/librespeed/speedtest) in your LAN (e.g. whereever your jellyfin runs on), which is much more reliable and doesnt require a fast internet connection.

**Comment by misterbit-pro** [comment]
> > > > Well the B8 has 100MBit Ethernet, so if you are not using fast WiFi that will be your bottleneck.
> > > 
> > > 
> > > I am using wifi. But jellyfin has a software side limit of 120Mbps. This must be the problem in my opinion. This only happens if the bitrate is really high, only at some scenes. Because i downloaded the Dolby Vision Demo Pack and some trailer work and others don't. Too bad, but i already added a feature request to the fider platform to support higher qualities than 120Mbps. I think this issue can't be fixed with buffering. So the issue can be closed.
> > 
> > This has nothing to do with the transcoding limit? I stream UHD Bluray remuxes quite successfully, but the TV needs to be on a 5Ghz WiFi network that will do the appropriate speed. I have a Ubiquiti nanoHD and get about 300 Mbps on the TV. You can use fast.com in the webbrowser for example to easily test the speed to the internet (given that your home internet is fast enough to out pace your WiFi link).
> 
> You can also run [librespeed](https://github.com/librespeed/speedtest) in your LAN (e.g. whereever your jellyfin runs on), which is much more reliable and doesnt require a fast internet connection.

My jellyfin server lives not in my home network, but in the internet (hosted on a server in a data center). So the internet speed is important in my my case.
