### ISSUE TITLE
Next steps of this client?

### ISSUE THREAD

**Issue by moritz31** [jellyfin/jellyfin-webos#2]
Hey, 

what are the next steps here, maybe want to jump into this, but not sure where to start? Anything planned until now?

Regards
Moritz

**Comment by dkanada** [comment]
Most of the required work will compatibility improvements for TV devices in the web repository. @dmitrylyzo has been submitting a lot of pull requests for Tizen support that will also inadvertantly benefit the WebOS client.

**Comment by dkanada** [comment]
@EraYaN was also working on WebOS if I recall correctly, and most of the issues were missing features in the embedded web browser.

**Comment by EraYaN** [comment]
Well it's mostly a problem for older versions of webOS new version are just "normal" chromium. The main blocker for this client is the navigation. Like the phantom focus objects etc.

**Comment by Narfinger** [comment]
Update on this: Some of the navigation is working with the latest web release. However, there are still some bugs.

**Comment by Rudde** [comment]
Is there any reason this is not in the LG Content store?

**Comment by Narfinger** [comment]
There are a couple of problems with the current client, all rooted in the jellyfin/jellyfin-web. I am not quite up to date on the status of these issues. There is also a bunch of testing needed on the different WebOS versions.

**Comment by dkanada** [comment]
Supposedly WebOS 4.0 works fine now and 3.0 may or may not work. The largest hurdle is creating the build scripts used to automate releases.

**Comment by JustAMan** [comment]
Also note that WebOS 2.0 or older support is not there (being worked upon), and remote navigation might need some attention (most stuff should work with airmouse remote, but not all LG TVs are equipped with it, plus I doubt we'll pass LG Store checks if normal remote won't work the way it should).

**Comment by crisp2u** [comment]
@dkanada Do you guys need any help with the automatic release ? I have a LGTV with WebOS 4 and I have experience with devops and release process but I'm new to the WebOS ecosystem

**Comment by JustAMan** [comment]
It's in a state which is far from a release, we need to pass rather strict requirements' list when submitting to a store, and the app (as it's just a view over installed server) won't be updated a lot after that.

So we're mostly fixing web part of the equation before we can submit the app to the LG store.

**Comment by davidsaraiva** [comment]
Hi, are you guys having in consideration the navigation in the menus using the arrow keys of the TV controller? I tried in the webOs browser and they are not working correctly. I'm using the TV SJ850V (SW 05.80.55). Is there any way I could test what you already have?

**Comment by Narfinger** [comment]
I think the general feeling is to wait for the 10.6 release of jellyfin and then submit it.

**Comment by alex9099** [comment]
Interesting, i almost convinced some friend who use plex to switch to jellyfin, but yeah, the lack of the app on the store is holding them back. For me that's not a real problem, i just upload it to the tv (i have android tv though), but my *not that tech savvy* friends won't really do that, as on lg and samsung it seems like a developer account and all is needed :D

**Comment by iMartyn** [comment]
Yeah, even as a tech-savvy person, I'm waiting for TV support before switching... although the perfect time to switch is now as we're in the summer lull of TV shows, so loosing where I am in series' is not a factor.

**Comment by anthonylavado** [comment]
Closing for now, for current publishing progress we'll follow along in #28.
Once we're through that hurdle,we'll reevaluate what has to be done next.
