### ISSUE TITLE
DTS gets re-encoded for no reason 

### ISSUE THREAD

**Issue by Dark-Noir** [jellyfin/jellyfin-webos#212]
I got a mkv with DTS audio which gets re-encoded to AAC for no reason.
When I disable audio re-encoding for my user it just plays fine directly as DTS
TV: LG OLED C3

Has probably nothing to do with this issue but why get my AV1 video re-encoded to HEVC when my PGS subtitles not compatible?
I disabled AV1 encoding because lack of hardware power, but why is it needed to re-encode the whole video only because of the subs? 
It's more a general question 😅

**Comment by Dark-Noir** [comment]
> #172 already fixed by [jellyfin/jellyfin-web#5053](https://github.com/jellyfin/jellyfin-web/pull/5053)
 Is there any known ETA on this, the merge is already few months old?

> PGS are image-based subtitles, which are not generally supported. So they must be encoded into the video stream - transcoding.
Ah okay, makes sense, thanks for clarifying ^^

**Comment by anthonylavado** [comment]
It is part of the 10.9 release, currently expected for end of April.

**Comment by jothgard** [comment]
> It is part of the 10.9 release, currently expected for end of April.

Is PGS supported now? Have installed Jellyfin on my OLED LG, seems to force re-encoding with PGSSUB, but works fine with SUBRIP.
