### ISSUE TITLE
No longer available on webosbrew repo

### ISSUE THREAD

**Issue by reyqn** [jellyfin/jellyfin-webos#217]
It seems like webosbrew checks https://github.com/jellyfin/jellyfin-webos/releases/latest/download/org.jellyfin.webos.manifest.json which doesn't exist for the new release.

It's nice to have the app available on the lg store, but why not on both?

**Comment by anthonylavado** [comment]
Sorry, I forgot that it needed that file! It's been a while. I'll add it to the release.

**Comment by anthonylavado** [comment]
Hey there! Thanks for your patience. I added the manifest, so it should pick up on their next sync.

**Comment by reyqn** [comment]
Thanks! The app is back now
