### ISSUE TITLE
Projector - webOS 6

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin-webos#223]
Hi there,
First of all thanks a lot for making Jellyfin available on LG WebOS!

However I can't find Jellyfin in the content store on my LG HU715QW UST projector...  I tried changing the country (I tried with Germany, France and USA) but it did not fix the issue. 

My projector has WebOS version 6.3.0-5102 (kisscurl-kavir).

_Originally posted by @GorgiAstro in https://github.com/jellyfin/jellyfin-webos/issues/169#issuecomment-2054008200_

**Comment by avionics75** [comment]
Same issue here with a LG projector on WebOS 4.5, the app doesn't show in the LG content store (France, Germany, USA etc stores).
Funny fact, I tried to reinstall it through Homebrew, and it's throwing an SSL certificate issuer error, so not able to get Jellyfin again :(

**Comment by Tommycasta** [comment]
Hi, 
Same issue here with the LG Cinebeam q. The projector was just recently released so understandable its not on the store. It runs webOS 6. 
Thanks :)

**Comment by Tommycasta** [comment]
The app is now added for my projector. Thank you!

**Comment by GorgiAstro** [comment]
Many thanks !
