### ISSUE TITLE
Black Screen After conect

### ISSUE THREAD

**Issue by cdoblas-eng** [jellyfin/jellyfin-webos#226]
Hi guys, I have installed Jellyfin on my LG OLED65C34LA with webOS 23 - 8.3.0-1516 through LG CONTENT STORE and when I set the server address it stays on a black screen permanently, It's not a problem of server because I can connect to the server with others jellyfin clients. I have been testing and downloaded the WebOS TV 23 Simulator with the source code and happens the same, here I leave a video.

https://github.com/jellyfin/jellyfin-webos/assets/128298475/c0366a5d-8c22-4bf1-932e-7401f0d6e168

**Comment by dmitrylyzo** [comment]
Are there any logs (console) when using webOS Simulator? _I haven't tried it._

**Comment by keesfluitman** [comment]
@cdoblas-eng You closed this as completed, but can you tell us what was wrong? How can i fix this or troubleshoot this?

**Comment by cdoblas-eng** [comment]
It was happening because my router was not routing my devices correctly. I changed it and the problem was solved.

**Comment by keesfluitman** [comment]
Oke ill try the security headers in my ssl.conf that i have enabled for my nextcloud instance. The docs mention that these can break webos on lg.

**Comment by nebb00** [comment]
I have the same issue, no idea why its happening

**Comment by draft13** [comment]
> I had the same issue. But narrowed it down to this header causing the problems `add_header X-Frame-Options "SAMEORIGIN" always;`

removing this from my nginx config did the trick for me.
