### ISSUE TITLE
Episodes wrongly displayed

### ISSUE THREAD

**Issue by Deagarys** [jellyfin/jellyfin-webos#228]
When going to a series, and clicking on a season, the episodes images are seen but look weird. There is not title or episode number displayed.

**Comment by dmitrylyzo** [comment]
Browser extensions?
Some of them could break things.

**Comment by dmitrylyzo** [comment]
Please provide more information.
What TV model?
Jellyfin version?

**Comment by Deagarys** [comment]
TV: LG OLED65G36LA
Jellyfin: 10.8.13

**Comment by dmitrylyzo** [comment]
> No custom css but, I do have a theme called ultrachromic using skin manager

It's also a kind of custom CSS. AFAIK, these themes don't always support TV display mode -  they are mostly tested on Desktop/Mobile.

To find out if the theme is causing the problem, try on TV, `Settings` -> `Display` -> enable `Disable server-provided custom CSS code` -> `Save`. You may need to restart the app.

**Comment by Deagarys** [comment]
It indeed is caused by the skin i am using. I will close this issue now since it is not caused by the client.

Thank you.
