### ISSUE TITLE
Question - how to get logs or inspect jellyfin-webos when it is running on the TV?

### ISSUE THREAD

**Issue by ammgws** [jellyfin/jellyfin-webos#235]
I have an issue where [files that need transcoding do not play](https://github.com/jellyfin/jellyfin-web/issues/5068) in the webos client on my 2018 year LG C8 when it is served by v10.9.x but work fine with both v10.8.13 and in the WebOS simulator on my PC.

The server logs do not indicate any issue with transcoding itself so I want to check the TV side.

I ssh'd into the TV but could not find any accessible log files. 

The other thing I tried was using `ares-inspect` to connect to the webos client running on the TV and analysing it on my PC, but the version of chrome used by my TV is too old (79) for the inspect feature to work with the versions of Chrome/Chromium that I can install on my PC.

Is there anything I am missing with respect to getting more logs from the TV side?

**Comment by dmitrylyzo** [comment]
> the version of chrome used by my TV is too old (79) for the inspect feature to work with the versions of Chrome/Chromium that I can install on my PC.

The same problem for Tizen. You can download Chrome 79 - iirc, I used this list: https://github.com/Bugazelle/chromium-all-old-stable-versions/

**Comment by ammgws** [comment]
I tried installing chromium 79 from Arch Linux archive package repo but by itself it seems like that is not enough for it to function because the system dependencies it requires are now too new or perhaps missing.

**Comment by dmitrylyzo** [comment]
It seems to work on Ubuntu 22.04, but I have to use the `--no-sandbox` option.

I also use a separate data folder:
```
.
├── chrome89
├── chrome-data      <-- Chrome data folder
├── chrome-linux     <-- Chrome 79
├── chrome-linux.sh  <-- launch script
├── CLI
├── Emulator
└── Resources
```
_chrome-linux.sh:_
```sh
#!/bin/bash

APP_PATH=$(readlink -f "$0")
APP_DIR=$(dirname "$APP_PATH")
CHROME_DIR="$APP_DIR/chrome-linux"

LD_LIBRARY_PATH="$CHROME_DIR:$LD_LIBRARY_PATH" "$CHROME_DIR/chrome" --user-data-dir="$APP_DIR/chrome-data" --profile-directory=Devel79 "$@"
```

**Comment by ammgws** [comment]
Thank you, was able to do it with Google Chrome instead of Chromium.

Put a PKGBUILD here for anyone else wanting to install it on Arch Linux: https://gist.github.com/ammgws/f98af057651854b4312173bf750fd47c
