### ISSUE TITLE
Media stuck on start in infinite loading on webos 5

### ISSUE THREAD

**Issue by szbotms** [jellyfin/jellyfin-webos#238]
I installed the Jellyfin app (version 1.2.2) on my webos 5 TV from the content store. Set up the server, but once I try to play most of the media, the player loads, but stuck showing a loading indicator. I cannot exit the app or bring up the controls for the player, nor go back to the media list, I'm only able to exit the app from there.

When I use Jellyfin from the built-in web browser of the OS, it works just fine. I found some other issues which suggested that the reverse proxy can be an issue. I tried connecting to it directly using the server's IP, but the same issue appears.

If you need any logs, please let me know, but please include some guides on how can I get them.

**Comment by dmitrylyzo** [comment]
Try disabling `UserSettings / Playback / Prefer fMP4` on the TV (https://github.com/jellyfin/jellyfin-webos/issues/236#issuecomment-2196909372).

**Comment by szbotms** [comment]
@dmitrylyzo Thanks, that solved the issue. It still keeps just loading using reverse proxy, but I have not done any specific configuration to traefik to solve it, so that should be straight forward from the provided examples I guess. Or I'll just keep using direct IP as it's on the local network.

Thanks again!
