### ISSUE TITLE
here is a link on how to set it up and working on lg.

### ISSUE THREAD

**Issue by Drwarfare** [jellyfin/jellyfin-webos#25]
[](https://www.youtube.com/watch?v=jO-Mf9sLaWw)

link to a video

**Comment by ghostrobo282** [comment]
https://www.youtube.com/watch?v=jO-Mf9sLaWw

**Comment by cj2tech** [comment]
Cool. Is there a way to install it permanently without enabling dev mode?

**Comment by nielsvanvelzen** [comment]
@cj2tech please see #28 for more information about this. TRL;DR: not yet.
