### ISSUE TITLE
Can you add multilingual fonts?

### ISSUE THREAD

**Issue by ppskj178** [jellyfin/jellyfin-webos#251]
The font for ASS built into the jellyfin app doesn't seem to support korean.
When I play the korean ASS subtitles, all the letters come out as squares.
It would be nice to have the ability to use a font that supports multiple languages or specify the desired font.
I don't think it's a hardware issue because it looked fine when using plex.

**Comment by dmitrylyzo** [comment]
ASS usually requires a specific font (family) to look as intended.

You have 2 options:
1. Embed required fonts into the video file (MKV).
2. Use `Fallback Fonts`.

**Comment by ppskj178** [comment]
> ASS usually requires a specific font (family) to look as intended.
> 
> You have 2 options:
> 
> 1. Embed required fonts into the video file (MKV).
> 2. Use `Fallback Fonts`.


I don't want my ASS to output perfectly.
I just want the damn squares to come out as normal characters.

![image](https://github.com/user-attachments/assets/4befff47-87f3-4826-8093-81add227c8a5)
The attached image is the preview banner and I fixed it with the server settings, but the subtitles on my LG TV are currently the same as this.

It's too many and cumbersome to integrate all subtitles into MKV.
I don't know what #2 is, can you explain a bit more?

**Comment by dmitrylyzo** [comment]
> I don't know what #2 is, can you explain a bit more?

It is somewhere in `Dashboard / Playback`.
https://github.com/jellyfin/jellyfin-web/pull/1636

**Comment by ppskj178** [comment]
> > I don't know what #2 is, can you explain a bit more?
> 
> It is somewhere in `Dashboard / Playback`. [jellyfin/jellyfin-web#1636](https://github.com/jellyfin/jellyfin-web/pull/1636)

Oh perfect, just what I was looking for.
I didn't realize you had to set it on the server, I thought it was an option to burn subtitles into the video.
Thank you so much.
