### ISSUE TITLE
Photos do not display.

### ISSUE THREAD

**Issue by peterst1050** [jellyfin/jellyfin-webos#257]
I have installed jellyfin-webos client V1.2.2 on LG 2018 tv webos version 4.4.2-16.

Everything is fine (video plays, music plays) apart from viewing photos.  The thumbnails display correctly but when an image is selected the screen goes to black with no controls or image displayed.  I have waited 10-20 minutes but still no display. Pressing back on the remote takes you back to the thumbnails correctly. Accessing via the tv web browser is OK, the images display correctly.
The log file just shows the request and no errors.

Any suggesting as to debugging the issue would help?

**Comment by dmitrylyzo** [comment]
dub https://github.com/jellyfin/jellyfin-web/issues/5919
