### ISSUE TITLE
Question jellyfin-web

### ISSUE THREAD

**Issue by iNfRaSoNiC13** [jellyfin/jellyfin-webos#26]
Hello,
there is no issue I've tested it and its working great.
I have a question ( I am really new to all of this) , how to accesses and change manually some of the setting from jellyfin-web/src directory? 
I

**Comment by ferferga** [comment]
@iNfRaSoNiC13 What are you trying to do?

**Comment by iNfRaSoNiC13** [comment]
I am trying to edit some of the subtitles settings which are located in src Folder.

**Comment by ferferga** [comment]
@iNfRaSoNiC13 Why you want to do it in the code instead of the user settings? There are no settings for subtitles in src, they are just the web assets that make the web client work. Settings are stored in your browser, alongside your session data.

**Comment by iNfRaSoNiC13** [comment]
> @iNfRaSoNiC13 Why you want to do it in the code instead of the user settings? There are no settings for subtitles in src, they are just the web assets that make the web client work. Settings are stored in your browser, alongside your session data.

I did the same with my Samsung TVs. The reason is because there is a bug with the small subtitles size which you can see here.
Also I am adding different shadow for the subtitles.
Anyway if this is not possible for WebOS I'll move forward, thanks for your answers.

**Comment by dmitrylyzo** [comment]
WebOS app is just a wrapper. The difference with Tizen is that WebOS loads site directly from your server. So any changes on server will be visible on LG TV.

**Comment by iNfRaSoNiC13** [comment]
> WebOS app is just a wrapper. The difference with Tizen is that WebOS loads site directly from your server. So any changes on server will be visible on LG TV.

Now I get it. Thanks for the explanation.
