### ISSUE TITLE
Guide navigation for LiveTV is broken

### ISSUE THREAD

**Issue by habeebtc** [jellyfin/jellyfin-webos#261]
In the guide view of JellyFin WebOS client, it appears that navigation is broken in the Guide view where you can view programming for LiveTV.  See: Video.

Client version is: 1.2.2
Server version is: 10.9.11

Here's a video of it:

https://youtu.be/euCCTvqJRdc

I can't be certain that scrolling up and down is the only weirdness.  Probably someone should take a good thorough look through the UI and see what all works normally.

**Comment by dmitrylyzo** [comment]
I think this is the same as https://github.com/jellyfin/jellyfin-web/issues/5705

**Comment by HouseIndoril** [comment]
Also present on 10.10. Issue began in 10.9.X.

**Comment by dmitrylyzo** [comment]
dub https://github.com/jellyfin/jellyfin-web/issues/5705
