### ISSUE TITLE
Photos will not display

### ISSUE THREAD

**Issue by markster1700** [jellyfin/jellyfin-webos#263]
WebOS 5.40.61 and Jellyfin 10.10.0 10.9.11 release.
Any photos would not display, only black screen. However, when using LG browser it works.

**Comment by dmitrylyzo** [comment]
dub https://github.com/jellyfin/jellyfin-web/issues/5919

**Comment by markster1700** [comment]
What does it mean not planned in your answer? Does it mean that you will pull WebOS Jellyfin of the repository?
I don't understand what that means. It is obviously a BUG since it does work in a LG browser and the client is just a wrapper. Please clarify .

**Comment by dmitrylyzo** [comment]
WebOS app is just a wrapper. The bug should be fixed in the Web repo. Moreover, this issue also occurs on Tizen.

**Comment by markster1700** [comment]
Since many complained about the same issue and you already know I would have assumed that you as key developer of the wrapper would communicate directly with other developers and let them know. It would have been more efficient. Sure we’ll can open issue with that group. Is that what you want us to do?

**Comment by dmitrylyzo** [comment]
> Sure we’ll can open issue with that group. Is that what you want us to do?

It is already there - https://github.com/jellyfin/jellyfin-web/issues/5919
