### ISSUE TITLE
“Resume” does not work

### ISSUE THREAD

**Issue by luisiam** [jellyfin/jellyfin-webos#27]
Just compiled and install the app on my OLED65CXPUA. Server version is 10.5.5. Whenever I hit “Resume” on the TV app, the video does not start from where I left off. It always starts from the beginning. Using the “Play” button will do the same thing.

**Comment by pixwebagency** [comment]
I have the same problem on one of the three TVs.  Jellyfin version: "10.6.3" Windows 10 64 bit ( I tried on debian server too) Jellyfin for WebOS 0.2.2
Resume doesn't work even if I start playback from android or ios app. This problem is only on LGwebOSTV 32"

**Comment by dan2wolf** [comment]
For me is the same. It always starts from the beginning when I press resume. 
My Jellyfin version: 10.5.3. The problem is on my LG TV OLED55C9PLA webos 5.00.10

**Comment by elvis0288** [comment]
Is there any solution for this? When I try it on the browser it does resume but with the app, it will always start for 0

**Comment by TimMods** [comment]
To me it seems that Jellyfin on WebOS isn't able to resume direct play videos, **some transcoded videos do resume for me**. I've been digging into this once and my conclusion was that WebOS is missing some ES6 Javascript modules for this to work, not sure tho.

**Comment by anthonylavado** [comment]
Superseded by #46.
