### ISSUE TITLE
Live TV Guide - Unable to scroll

### ISSUE THREAD

**Issue by owenashurst** [jellyfin/jellyfin-webos#271]
I've noticed on the latest version, I'm unable to scroll down the Live TV Guide. It seems like the selection is highlighting programmes/channels  as you press the down arrow on the TV remote, however it goes off-screen as you get to the bottom and the guide doesn't scroll.

**Comment by dmitrylyzo** [comment]
Duplicate of https://github.com/jellyfin/jellyfin-web/issues/5705
