### ISSUE TITLE
Content Fails to Play [webOS 1.0, 2.0]

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin-webos#45]
**Issue**
During certification testing, devices running LG webOS 1.0 or 2.0 could fail to playback items under certain circumstances.

**Notes from Testing**
> Problem: Black screen is displayed when playing random video content.

> Opinion: After selecting the Music UI Button, app does not play when the random music content is played. / The same issue is reproduced when random video content is played after selecting the TV Shows UI Button.

> Expected: When random video content is played, it should be played normally.

**Next Steps**
It is possible that this may happen on other versions but LG did not indicate this in their test notes. In the notes provided, there was a video showing the tester using a magic remote in pointer mode for navigation. 

_For internal (Jellyfin) testing:_
- Install more webOS emulators and test with app.
- Check equipment list for team members with webOS 1.0/2.0 equipment and ask them to test with magic remote.

_For community help:_

If you have a webOS 1.0 or 2.0 device (or any version), please let us know if you are able to test this using the steps above. If you need a compiled IPK to install, please let me know.

You can use the public demo server, https://demo.jellyfin.org/stable.
The username is `demo`, with no password. If you need a compiled IPK to install, please let me know.
Note that the public server is reset on the hour, **every hour**. It is recommended to avoid testing at that moment, as it will likely result in a connection error. This does not apply to our internal testing server.

**Possible Fixes**
The demo servers are hosted in Toronto, so latency may be an issue for the LG test team, who are located in Korea. We may consider setting up an alternate test server just for this purpose.

**Comment by rfvizarra** [comment]
Hi  @anthonylavado 

I have an LG TV with Web OS TV 2.2 not sure if you need to test with that version. If so, please let me know how can I help.

**Comment by Brice187** [comment]
Do you need the compiled IPK? Please check the docs on how to install the dev version on your TV ;)

**Comment by rfvizarra** [comment]
> Do you need the compiled IPK? Please check the docs on how to install the dev version on your TV ;)

If you can provide the IPK that would be great. I have never done any development for WebOS 
I guess I'll have to follow the instructions from https://webostv.developer.lge.com/develop/app-test/

**Comment by BachoSeven** [comment]
FWIW, I have just compiled from source and tested the app on a LG tv with WebOS 4.3.0-9703, and it seems to work wall(no connection errors, content plays well). Thanks for making this!

**Comment by Pantar2205** [comment]
Is this item stalled until there is someone with a v1 or v2 tv is available to test it out? I presume those models of tv are pretty old, can't buy them anymore and might be hard to come by. How would testing proceed on version of a product you can't get anymore?

**Comment by anthonylavado** [comment]
@Pantar2205 LG tests whatever models we tell them we support, and their testing lab has a warehouse of them to work with. In addition, the webOS SDK package includes emulators for all major versions of webOS.

**Comment by anthonylavado** [comment]
Closing in favour of #92.
