### ISSUE TITLE
Resume Does Not Work [webOS all]

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin-webos#46]
# Update
The issue appears to be resolved after manually applying this fix: https://github.com/jellyfin/jellyfin-web/pull/2799.
While this is not present in the currently released version of Jellyfin, it will be available in any future version. Since the webOS app loads the HTML interface from the server, you can manually apply the update by rebuilding web with that fix, or downloading an alternate version (see below).

----
## Previous History

**Issue**
During certification testing, devices running LG webOS 4.0, 4.5, 5.0, and 6.0 could fail to resume playback, and instead start over from the beginning.  Both the resume and play buttons will appear to be highlighted at the same time.

**Notes from Testing**
> Problem: Replay does not operate when playing random video content.

> Opinion:-

> Expected: Replay should operate when playing random video content.

**Next Steps**
It is possible that this may happen on other versions, such as webOS 1.0, 2.0, 3.0, and 3.5. LG indicated that they did not test on these versions due to #43 and #45. In the notes provided, there was as video showing the tester using a magic remote in pointer mode for navigation.

_For internal (Jellyfin) testing:_
- Install more webOS emulators and test with app.
- Check equipment list for team members with any webOS equipment and ask them to test with magic remote.

_For community help:_

If you have a webOS device, please let us know if you are able to test the issue listed above. If you need a compiled IPK to install, please let me know.

You can use the public demo server, https://demo.jellyfin.org/stable.
The username is `demo`, with no password. If you need a compiled IPK to install, please let me know.
Note that the public server is reset on the hour, **every hour**. It is recommended to avoid testing at that moment, as it will likely result in a connection error. This does not apply to our internal testing server.

**Possible Fixes**
This may be tied to the TV interface from the jellyfin/jellyfin-web UI, and may require an updated release with a fix in order to correct it. More investigation is required to determine if this is the case.

The demo servers are specially set up to use content that should not require transcoding, both to ensure that playback is fast and quick, as well reducing hardware demands on the demo server.  According to #27, this issue may be specific to direct play content.

**Comment by dovecode** [comment]
As mentioned on #48, I can to help if you can provide an IPK. I am on WebOS 06.00.05.

**Comment by dovecode** [comment]
I tried this on my own server and I couldn't reproduce the problem. I did try to disable transcoding, but I'm not sure if the change "took". When the public demo server gets fixed I can try with that one.

What I did notice was that the play/resume buttons are confusing, which _could_ have contributed to the bug report.

A movie that doesn't have a resume point first opened, this is how the play button presents itself:

![image](https://user-images.githubusercontent.com/16987409/115089683-c7fc5d80-9ee0-11eb-85f0-58800ab4c693.png)

Here, the Play button is both highlighted and has a large circle around it.

Clicking the right button a few times and you get this:

![image](https://user-images.githubusercontent.com/16987409/115089708-dea2b480-9ee0-11eb-9a31-32a12ee02056.png)

So here the Mark Played button is highlighted and the play button is still large, but now has the same color as the current selection. This is quite confusing from a UX perspective.

Playing for a bit and then going back to the menu, you get this:

![image](https://user-images.githubusercontent.com/16987409/115089818-20cbf600-9ee1-11eb-83e7-c85f48a724f2.png)

Now the Play From Beginning button is highlighted and the larges button. In order to resume, you have to click left and you get this:

![image](https://user-images.githubusercontent.com/16987409/115089850-39d4a700-9ee1-11eb-8812-518c9c5e8f18.png)

This raises a number of concerns:

1. There's a "default" (enlarged action). It is unclear why this even exist and how this would be activated other than navigating to it.
2. The default action for a movie that has a resume point is Play From Beginning. Why?
3. The current selected action item is either round and white or square and blue, while the default action is blue when not selected. Very inconsistent.

**Comment by anthonylavado** [comment]
@dovecode Thanks for the comments. We reviewed our server configuration yesterday and the public demo server _should_ be working. Regardless, this is useful feedback here, so I can work with it.

**Comment by dovecode** [comment]
@anthonylavado I tried to connect to https://demo.jellyfin.org/stable from my TV (WebOS 6.0.5) today and I still get the generic connection error.

**Comment by anthonylavado** [comment]
Connectivity discussion should continue in #43 :-)

**Comment by elvis0288** [comment]
i tested this on my personal server with multiple movies and multiple different ways and every time i press the resume button the movie/tvshow will start from the beginning.. it is never resuming for me

**Comment by DpunktKpunkt** [comment]
Double highlighting / selection of play and resume button as mentioned by dovecode confirmed on real TV and emulator (both webOS 4.0). 
This also occurs if a movie has no resume point. Here play button stays selected when you move on to theater icon, favorite icon and so on.

**Comment by dovecode** [comment]
I want to highlight @elvis0288's post, though. It seems that there truly is a resume issue, separate from the UX concerns I raised in specific circumstances. We should probably address both, but maybe adding a separate "button UX" issue would be better and track the issue that @elvis0288 found on this issue...

**Comment by elvis0288** [comment]
If you guys want me to do something specific and give you some logs let me know

**Comment by elvis0288** [comment]
for the example @dovecode  give, i am actually using the magic remote and going directly to the resume button and pressing it and it does not work it goes back to the beginning.. i also tried going left and left and that does not work.. also try going down up browse a little bit then come back to resume button and still not working.. let me know if you guys want me to do something specific or if you add some debugs i can compile and install on my tv to test

**Comment by anthonylavado** [comment]
Just popping in to say we're still working on this, piece by piece. Going to submit soon, just have to get the resume and playback issues worked out. We updated the server recently so we're testing against those fixes.

**Comment by elvis0288** [comment]
hello @anthonylavado  i grabbed the latest branch and i am still having this issue on my end.. is this on a different branch that i can use to also test?

**Comment by acidtracks** [comment]
Hello,
any update on this issue. Do you need help to resolve this faster.

**Comment by sqr** [comment]
Hello,
I am also compiling the IPK and sending it to my TV for everyday use, is there any way I can help testing for a solution or finding a fix?

Thanks

**Comment by akrabi** [comment]
@anthonylavado is anyone working on this already?
I am able to repro this using 6.0 emulator and the demo server.
I can start looking into it and try to find a fix but I want to make sure there's no duplicate work...

**Comment by anthonylavado** [comment]
I'll be pulling @daullmer's fix for jellyfin-web into a custom deployment for our test server (see https://github.com/jellyfin/jellyfin-web/pull/2799/).

This will resolve the button highlighting issue. I'll have to test if the resume function works properly after.

**Comment by anthonylavado** [comment]
I should add: The fix would be in the next released version of Jellyfin, but since there isn't a maintenance release currently planned, it wouldn't be out for the general public. The benefit of this being a web issue is that we can still try to get the app released by solving the issue on the test server, and then users will automatically have the issue fixed the next time they update their Jellyfin server.

**Comment by daullmer** [comment]
@anthonylavado I have tested it on a LG TV (with webOS 5.0.03 without a Magic Remote and resume works.
I tested the same tv against the stable demo server and resume worked as well.
The weird thing is, I recall having exactly this issue on the same tv that I can't resume items and they will always play from the beginning

**Comment by anthonylavado** [comment]
This is excellent news. We're trying to update the demo server to have this functionality (thank you @oddstr13), but as we now minify the websource at compile, it's been... tricky. We'll still hack away at it. Thank you @daullmer!

**Comment by anthonylavado** [comment]
I have manually applied the controls UI fix to the private demo server, and it indeed does appear to be working. Will keep this issue open for tracking and update the OP to provide details to others.

**Comment by acidtracks** [comment]
Thats a really good job. So do you planned toi launch the app on LG store ?

if you need some more help do not hésitante

Regards

Le ven. 13 août 2021 à 23:05, Anthony Lavado ***@***.***> a
écrit :

**Comment by renini** [comment]
I tried the jellyfin-web from last succesfull [master build](https://dev.azure.com/jellyfin-project/jellyfin/_build/results?buildId=34631&view=results), but still having these issues. Can anyone else confirm?

I'm running jellyfin dockerized, so in order for me to "patch" jellyfin-web i just downloaded the production.zip artifact produced by the pipeline and mount this jellyfin-web over with "/opt/jellyfin/web:/jellyfin/jellyfin-web" in docker-compose. 
This seems enough to deploy a newer jellyfin-web, but maybe i'm missing something, or this bug got reintroduced back later again. Can anyone point me to a fixed jellyfin-web.zip?

**Comment by jfeil** [comment]
Tried it yesterday with the current linuxserver nightly build (which stated 10.8 and had the visual bug fixed), but resuming didn't work for me either... Pressed the resume button and it started again from the beginning...

**Comment by renini** [comment]
@anthonylavado can you point me to the jellyfin-web version deployed on the demo site? As that one seems to be working fine.

**Comment by crobibero** [comment]
The demo site is currently running 10.7.7 (soon to be 10.8), source here: https://github.com/jellyfin/jellyfin-web/tree/release-10.7.z

**Comment by renini** [comment]
@crobibero thanks for pointing to the version. Somehow even with 10.7.7 deployed at my own install the resume on LG doesn't seem to work. I'm a bit puzzled about what the difference is with the version i tried on the demo site before then. Anyone else got a working solution?

**Comment by jfeil** [comment]
Also even if you connect the Android app to the WebOS app and try to resume a video, it still plays it from begin :(

**Comment by JustasBud** [comment]
Same issue for me, clicking on resume playback with magic remote starts playback from the beginning. Checked stats and the only video which worked on resume was the one which was transcoded; direct play did not resume.
Logged into the demo server @ https://demo.jellyfin.org/stable with LG webOS v5.

**Comment by jfeil** [comment]
Just tried with the 1.8.0 Update: The problem is still there (at least with non transcoded content).

**Comment by dmitrylyzo** [comment]
When testing https://github.com/jellyfin/jellyfin-web/pull/3724 in emulators, I found that webOS 4 is the only one that doesn't resume.
webOS 1.2, 2.0, 5.0, 6.0 emulators work as expected without any hack - they seem to support `#t=...` argument.
webOS 3 emulator is buggy as hell - unreliable.

_To be clear, please make sure you see the `Replay` button - in this case `Play` is "resume". If `Replay` is missing, you have a problem with websockets._

**Comment by jfeil** [comment]
If you like, I would be able to give you a video call or sth like that, to show you my issue!

**Comment by jfeil** [comment]
It's a C9 with 5.20.09

**Comment by Kivylius** [comment]
It looks like /jellyfin-web/pull/3724 has fixed the issue with auto play set to ‘auto’ as a new less hacky solution for webOS. Good news is that was been merged to 10.8.x. has anyone tested that fix yet?

**Comment by jfeil** [comment]
No, did not yet test this new release! Will do it when I come home later today :)

**Comment by jfeil** [comment]
Yesss, it works now! 10.8.1 fixed it!

**Comment by anthonylavado** [comment]
Yep, 10.8.1 has the web fix needed.

The link, for posterity: https://github.com/jellyfin/jellyfin-web/pull/3724#event-6881157343

**Comment by mhorst00** [comment]
I have installed the Jellyfin app for WebOS recently on a LG TV with version 05.50.15. Resuming playback on non-transcoded files is still broken the way it has been described here. Transcoded content does not have this issue.

Jellyfin server is on version 10.8.13, so the mentioned merge should be included. Is there something I can provide to make debugging of this easier?
