### ISSUE TITLE
Error -27 at startup

### ISSUE THREAD

**Issue by IshFx** [jellyfin/jellyfin-webos#52]
Hello,

First of all, thank you for this app and jellyfin in general.

So i cloned this repository, compiled it with webos sdk then uploaded it to my TV (Webos 5.2.1-2521).
After running the app, i entered my jellyfin server (https://media.mydomain.tld) then pressed "Connect".
The app responded with an error screen saying "Loading not possible" and en error code : **-27**.

I restarted the app and tried with the demo server (https://demo.jellyfin.org/stable) : It worked !

What does this error code mean ? Did i forget something in my jellyfin server conf ?

Thanks in advance!

**Comment by IshFx** [comment]
It seems that the issue comes from a closed port (7359/udp). Now everything is working !

**Comment by mekwall** [comment]
> It seems that the issue comes from a closed port (7359/udp). Now everything is working !

@IshFx How did you figure this out?

**Comment by kwaio** [comment]
Same error here. Forwarding udp/7359 didn't help

**Comment by iwatch-x** [comment]
i got the same error did someone find out whats wrong?

**Comment by ypid** [comment]
I found that the webserver hardening `X-Frame-Options "SAMEORIGIN"` that DebOps has enabled by default resulted in this error. With `X-Frame-Options` absent in the HTTP response headers Jellyfin works well for me on webOS. My exact setup that works with webOS can be reproduced with Ansible and DebOps. Jellyfin Ansible role: https://github.com/ypid/debops/tree/add/jellyfin/ansible/roles/jellyfin

So things you should check: What is your reverse proxy, thing that gives you HTTPS, whatever is between Jellyfin and the TV doing? Does it insert hardening headers? You can check with `curl -I -X GET $jellyfin_url`. It must not show `X-Frame-Options` as set to `SAMEORIGIN`.
