### ISSUE TITLE
Status for everyone?

### ISSUE THREAD

**Issue by HellFall999** [jellyfin/jellyfin-webos#54]
I am no developer. I followed Jellyfin for 2.5 years by now. I followed trough several forums, boards, and so on. All closed. Now github. Nice.

Still no app an LG TVs. HOW MUCH MONEY DO I HAVE TO PAY to get an jellyfin app on LG TV? 

2.5 years not watching any movies anymore because no working app on LG TV?

No, thats it. I am done with open source. I am done with waiting. I am done. I will pay emby a livelong account. I tried my best to support jellyfin. Bye guys.

**Comment by red0888** [comment]
> I am no developer. I followed Jellyfin for 2.5 years by now. I followed trough several forums, boards, and so on. All closed. Now github. Nice.
> 
> Still no app an LG TVs. HOW MUCH MONEY DO I HAVE TO PAY to get an jellyfin app on LG TV?
> 
> 2.5 years not watching any movies anymore because no working app on LG TV?
> 
> No, thats it. I am done with open source. I am done with waiting. I am done. I will pay emby a livelong account. I tried my best to support jellyfin. Bye guys.

Bro just use the web browser lmao. I'm using it with my LG TV and it works really well

**Comment by anthonylavado** [comment]
I'm sorry to hear that the free and no cost software developed by people in their spare time has failed to meet your expectations. In your search for a way to communicate with us or follow our progress, you may have missed our [contact page](https://jellyfin.org/contact/) which lists our Twitter account (which I also run), our subreddit (which most members of the team are on, along with ~22k users), or the eight chat channels offered across three networks (Matrix, Discord, IRC). Using GitHub except for technical issues is not a requirement, and we even offer to open issues on user's behalf so they don't have to sign up if they don't need to.

I don't own an LG TV and my personal life has gotten in the way here, but I'll still try to get this released. Not that it seems that it matters. Have a good day. 🙂
