### ISSUE TITLE
Automatically transcode DTS audio to AC3 on newer TV models

### ISSUE THREAD

**Issue by whiteworthy** [jellyfin/jellyfin-webos#56]
First of all, this is the best app by far for webos, but it still has the same issue as Emby where it can't play DTS audio (since LG removed it for all 2020+ models).

As of right now Plex doesn't support subtitles (SRT/PGS) for 4K HDR content and Emby also doesn't have support for DTS audio transcoding, this project is our only hope. No idea what can be done since this is jellyfin-web but might as well give it a try, maybe even get a workaround.

Both Emby and Plex don't get many updates to fix issues and taking advantage of the constantly maintained Jellyfin project would be perfect for LG users, except this is the only thing lacking.

DLNA is not an option since LG's player lacks a lot of functionality (such as playing DTS audio).

**Comment by anthonylavado** [comment]
I'll find out where the playback profile is out together for this. So to be clear - DTS was present on prior models, but now is no longer present?

**Comment by whiteworthy** [comment]
Yeah, they didn't renew the license for all 2020 (and newer) models so if you direct play DTS the audio stream will be full mute. Plex fixes this by transcoding DTS to AC3 and Emby chose to do the same, but people are waiting for the Emby update for 13 months now and an update from their staff is nowhere to be seen...

**Comment by anthonylavado** [comment]
@whiteworthy Thanks for the heads up! So I checked with the team, and the conditions are built in the Web interface itself. I'll make a corresponding issue there to have a change put in for LG TVs that match the generation that drops support and newer.

**Comment by whiteworthy** [comment]
I did create my own transcoding profile however it only works on the built-in web browser since Jellyfin fails to recognize the webos app as an LG device, it only recognizes it as "Null" and gives it a default transcoding profile that direct plays everything instead of the correct one, I'm assuming you're able to fix this... I did try to use HTTP Headers substring as identification for the profile like below but it didn't work, maybe I'm doing it wrong and you're able to guide me, I captured the user-agent with Wireshark, I will also attach the revelant logs
[log.txt](https://github.com/jellyfin/jellyfin-webos/files/7024229/log.txt)
![image](https://user-images.githubusercontent.com/11664917/130296038-65e95f88-adb4-4a11-b920-e10f6de2ac89.png)

**Comment by anthonylavado** [comment]
Just for reference: https://github.com/jellyfin/jellyfin-web/pull/2942

**Comment by anthonylavado** [comment]
@whiteworthy The user agent thing seems to have been part of an LG update: https://github.com/jellyfin/jellyfin-web/pull/2781

**Comment by viennaa** [comment]
The fix provided in https://github.com/jellyfin/jellyfin-web/pull/2971 works. Before 10.8.0 is released, the only option is building it alone. I'am using the docker image with you could simply build from latest master in jellyfin/jellyfin. It works and DTS is transcoded. Here my confirmation comment:

https://github.com/jellyfin/jellyfin-web/pull/2971#issuecomment-984875530

**Comment by orangpelupa** [comment]
got this same issue on
serverVersion: 10.8.10
Operating System: Linux

webos client on LG CX. not sure the jellyfin ver, i dont know where i can see it. but it got no update pending.

jellyfin client complains that it didnt receive a compatible format from the server

**Comment by T3rm1** [comment]
Same here with a LG CX OLED TV. Is anyone going to fix this?
