### ISSUE TITLE
How to reset App settings? - Error Code: -27

### ISSUE THREAD

**Issue by zeigerpuppy** [jellyfin/jellyfin-webos#62]
```
modelName : OLED55G1PTA
sdkVersion : 6.2.0
firmwareVersion : 03.20.45
boardType : O20N_DVB_AJ
otaId : HE_DTV_W21O_AFABATAA
```

I installed org.jellyfin.webos successfully in developer mode.

The app was working well on the TV, however it has stopped working when I enabled "remember this server".

Now, whenever I launch the App, it displays the Error message, despite my server being up and functional (can browse jellyfin DLNA for instance on same TV) :

```
Error Code : -27
UNABLE TO LOAD
This may be a temporary issue.
Please try again later.
<Retry> <Exit App>
```

clicking either option brings up the error again.

I have tried, rebooting, uninstalling the App and reinstalling and looked around the file tree for a settings file to reset, but cannot find anyway to clear the application settings.

I think it's possible that the saved server URL may be invalid but it doesn't allow me to change it.

How can I reset the stored application settings?  I think that will allow the Jellyfin client to start again properly.

**Comment by zeigerpuppy** [comment]
I think this may be the same issue as #60

**Comment by anthonylavado** [comment]
I think you're right. Let's continue in that issue.
