### ISSUE TITLE
Create a GitHub release

### ISSUE THREAD

**Issue by Informatic** [jellyfin/jellyfin-webos#67]
Hey!

Following @tuxuser's CI release flow work, it would be nice if a version was bumped and then effectively pushed into GitHub release.

Then we could finally publish jellyfin-webos on [webosbrew apps repository](https://github.com/webosbrew/apps-repo).

Note that he seemingly forgot to add to the README:
`npm version [major|minor|path]` in root directory shall now apropriately bump version in both `package.json` and `frontend/appinfo.json`, and then put that into a commit/tag. Tag pushed to GitHub repo will create a "prerelease" release with `ipk`/manifest files, which then will need to be marked manually as final in [Releases tab](https://github.com/jellyfin/jellyfin-webos/releases).

**Comment by Brice187** [comment]
Would love to see this too! 

Is it possible to manually add the latest .ipk to the homebrew channel so I can permanently use jellyfin-webos without automatic updates? The licenses of jellyfin should allow this (imho).

**Comment by Informatic** [comment]
Sure we could do that without consulting with upstream, but we'd really like to have it here to not move stuff around multiple times. I hope someone sees that there's some interest in the community for that.

**Comment by anthonylavado** [comment]
@Informatic I'd be interested in helping make that happen. My main concern is only if this would hamper our chances of being published by LG once we submit it to the store (again).

Otherwise, I'll review your first comment and move forward with that.

**Comment by Informatic** [comment]
Well - if you *just* made an "internal" `v1.0.1` release, I don't think you are contractually obligated to ship every one of them to LG, are you?

I can imagine you'll need to send an update to them at some point anyway, since I see there were some styling changes impacting webOS v1/v2?

Also I would be surprised if updates themselves were as hard to pass through the QA testing as the original release (though I never published any app on Content Store)

**Comment by Brice187** [comment]
@anthonylavado: Creating a Github release does not affiliate you/jellyfin with an external project automatically :)

**Comment by brando56894** [comment]
Getting an official/easy to install client would be great. I just bought an LG A1 for my parents, and got rid of the Nvidia Shield that they were using (too many remotes, one for the shield, one for the sound bar, one for the TV. No CEC) and told them to just use the LG Apps. My dad asked where Jellyfin was and I told him that it wasn't available on LG TVs and he'd have to use Plex. The problem is Plex is setup to stream from my library and not their local NAS which has Home Movies on it and they wouldn't want to have to keep switching servers in the UI.

**Comment by anthonylavado** [comment]
Will do soon. The weekend is almost here...

**Comment by Perseusdehond** [comment]
I haven't heard of webosbrew, what is it and/or how does it work? Because it sounds like a way to get a Jellyfin app on my LG TV soon

**Comment by Informatic** [comment]
See https://webosbrew.org

Easiest way of getting Homebrew Channel (unofficial app "store") working
well is https://rootmy.tv - we will release an updated version in the
following week that should work on all current webOS versions, so stay
tuned.

**Comment by anthonylavado** [comment]
SDK had to be re-installed (I recently had to replace my main drive on my iMac), so I can cut a release tonight.

**Comment by anthonylavado** [comment]
@Informatic Does this help at all then? https://github.com/jellyfin/jellyfin-webos/releases/tag/v1.0.1

**Comment by Informatic** [comment]
Yes! That is perfect. I am going to file a change to webosbrew apps repo and it'll be downloadable for people with Homebrew Channel in a couple of minutes.

**Comment by Informatic** [comment]
@anthonylavado Ah! One other thing. Can you please untag "this is a prerelease" option in options for that Github release? We try to default to linking to "full" releases.

**Comment by anthonylavado** [comment]
@Informatic Done. Thanks for letting me know!

**Comment by Informatic** [comment]
Perfect. Everything is up now. Thank you very much for the support.

https://repo.webosbrew.org/apps/org.jellyfin.webos

![capture](https://user-images.githubusercontent.com/1131102/148704381-09fadb52-ffff-4ba6-8d10-3e3a8067e7d1.png)


In case you wanted to change the description/logo URL (I couldn't find any screenshots or such), just file a PR against this file:
https://github.com/webosbrew/apps-repo/blob/main/packages/org.jellyfin.webos.yml
