### ISSUE TITLE
Login Screen does not allow focus of connection data fields

### ISSUE THREAD

**Issue by Narfinger** [jellyfin/jellyfin-webos#7]
The login screen currently does not allow focusing of the connection data fields (ip address etc.) and hence not allowing them to edit on a standard remote.

Using Magic Remote this might work.

WebOS: 5:50.55

**Comment by EraYaN** [comment]
Mmm they should allow it. It's up on the remote twice, since the default focus is the connect button. In the end there will be one field. But what device are you testing this on? A 2019 model?

**Comment by Narfinger** [comment]
I think it is a new model. I am not quite sure as I got it from an agency used.
I tried the keycode sample app but that gives the correct keycode. Trying to change either to not have the navigation javascript or changing keydown to keypress does not seem to make a difference.
