### ISSUE TITLE
Jellyfin 1.0.1 @65UJ6309 (rooted) - Black screen after connect

### ISSUE THREAD

**Issue by DpunktKpunkt** [jellyfin/jellyfin-webos#74]
I just rooted a LG 65UJ6309 (FW 6.00.20, WebOS core 3.9.0-62906). Homebrew channel works and ssh connect is possible.
CA Certificates renewed with script from https://github.com/tf318/lg

Jellyfin Server 10.7.7 is behind nginx reverse proxy. Access from other devices (Android, Fire TV Stick, other LG TV (65UK6400)) without any problems.

After installing jellyfin 1.0.1 and entering my server URL (https://jellyfin.formyeyesonly.tld, public url with Lets Encrypt Certificate). I also checked the autoconnect box and clicked on connect.

Screen went black and stayed black. Rebooting and restarting jellyfin showed just the logo for a few seconds, then for a fraction of a second the connect screen was visible and then the screen went black.

Nginx log shows three requests:

```
X.X.Y.Z - - [15/Jan/2022:19:31:08 +0100] "GET /System/Info/Public HTTP/1.1" 200 234 "-" "Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.122 Safari/537.36 WebAppManager"
X.X.Y.Z - - [15/Jan/2022:19:31:08 +0100] "GET /web/manifest.json HTTP/1.1" 200 304 "-" "Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.122 Safari/537.36 WebAppManager"
X.X.Y.Z - - [15/Jan/2022:19:31:09 +0100] "GET /web/index.html HTTP/1.1" 200 1506 "-" "Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.122 Safari/537.36 WebAppManager"
```

As I checked the autoconnect checkbox it isn't possible for me to intercept the connect attempt any longer.

**Comment by anthonylavado** [comment]
While I don't have a direct answer for the black screen issue at the moment, the LG Developer docs say that uninstalling and re-installing an app should clear local storage (which is where we save the server info).

Are you able to try removing and reinstalling?

**Comment by DpunktKpunkt** [comment]
This tv isn't mine - I'll check it next week.
If that doesn't work, I will inject a wrong id into /System/Info/Public - auto_connect flag should be set to false that way:
https://github.com/jellyfin/jellyfin-webos/blob/master/frontend/js/index.js#L273

**Comment by DpunktKpunkt** [comment]
Just two ideas for the issue of providing a method to reset server connection (https://github.com/jellyfin/jellyfin-webos/issues/69):

- temporarily switch server id for a specific device at server side (additional option for device menu in index.html#!/devices.html)
- just before trying to auto_connect listen for a key event for one second

**Comment by DpunktKpunkt** [comment]
> Are you able to try removing and reinstalling?
I just tried it on my own tv (65UK6400, WebOS 4, FW 5.40.09) - local storage is deleted when app is uninstalled. That would be the most elegant way for others with an client side issue.

Hint for uninstalling jellyfin: Neither homebrew channel nor LG Content/My Apps (jellyfin isn't listed here) provide a way of uninstalling the app - just press home button, then the edit entry (most right icon), select jellyfin and press key up. Delete the app by the appearing "x".

**Comment by DpunktKpunkt** [comment]
Seems that jellyfin on LG TVs has some problem with nginx reverse proxy.
My other LG TV connects to jellyfin docker directly (http, port 8096). When I'm changing server to public url the same error occurs. (Tested with Lets Encrypt cert and ZeroSSL cert, so that's not the issue).

Other external devices using public url (Android tablet, iPad, Fire TV Stick, notebooks connecting via browser) connect without any issues.

**Comment by anthonylavado** [comment]
It's a bit of a mess but there's bound to be information in here: https://github.com/jellyfin/jellyfin-webos/issues/43

The short of it is that there could be a cipher config issue that is not letting your webOS 4 TV to connect.

**Comment by DpunktKpunkt** [comment]
Even though my TV successfully requested /System/Info/Public, /web/manifest.json and /web/index.html?

**Comment by DpunktKpunkt** [comment]
Increasing allowed ciphers according to #43 didn't help.
I then completely disabled https and set up reverse proxy for http:// - same strange effect. 3 successful requests from tv to nginx and screen stays black. Switching directly to jellyfin ip (http://<ip>:8096, autodiscovered) helps (at least for my tv in local network).

**Comment by DpunktKpunkt** [comment]
My test progress until now:

- nginx docker container from bitnami/nginx:latest, ip address 10.12.1.2, custom my_server_block.conf with http only (https://jellyfin.org/docs/general/networking/nginx.html)
- existing jellyfin (docker container from linuxserver/jellyfin), ip address 10.12.1.1
(both docker container are within same macvlan)

Access from computer to http://10.12.1.2:11180 (my listening port in that container) works
Access from 65UK6400 (WebOS 4) to http://10.12.1.2:11180 - just the 3 files from first post are successfully requested (http code 200), screen stays black, no loading indicator is shown

Maybe my jellyfin container is messed up and struggles with proxy (will be the next test scenario)

**Comment by DpunktKpunkt** [comment]
Fresh nginx container (bitnami/nginx:latest), fresh jellyfin container (jellyfin/jellyfin:latest):
`docker create \
  --name=nginx-test \
  -v /whitepool/nginxrp/my_server_block.conf:/opt/bitnami/nginx/conf/server_blocks/my_server_block.conf:ro \
  --restart unless-stopped \
  --network docker-vlan12 \
  --ip 10.12.1.2 \
  bitnami/nginx:latest

docker create \
  --name=jellyfin-test \
  -v /whitepool/jellyfinrp/config:/config \
  -v /whitepool/jellyfinrp/cache:/cache \
  --restart unless-stopped \
  --network docker-vlan12 \
  --ip 10.12.1.3 \
  jellyfin/jellyfin:latest`

my_server_block.conf (proxy entries copied from jellyfin documentation):
`server {
    listen 11180;
    server_name 10.12.1.2;

    access_log /opt/bitnami/nginx/logs/jellyfin_access.log;
    error_log /opt/bitnami/nginx/logs/jellyfin-error.log;

    set $jellyfin 10.12.1.3;

    location / {
        # Proxy main Jellyfin traffic
        proxy_pass http://$jellyfin:8096;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Protocol $scheme;
        proxy_set_header X-Forwarded-Host $http_host;

        # Disable buffering when the nginx proxy gets very resource heavy upon streaming
        proxy_buffering off;
    }

    # location block for /web - This is purely for aesthetics so /web/#!/ works instead of having to go to /web/index.html/#!/
    location = /web/ {
        # Proxy main Jellyfin traffic
        proxy_pass http://$jellyfin:8096/web/index.html;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Protocol $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
    }

    location /socket {
        # Proxy Jellyfin Websockets traffic
        proxy_pass http://$jellyfin:8096/socket;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Protocol $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
    }
}
`

Jellyfin initial setup done on computer. No plugins, media directories, ... just a plain fresh installed jellyfin.

Accessing jellyfin on computer: http://10.12.1.2:11180 and http://10.12.1.3:8096 is working
Accessing jellyfin on tv: http://10.12.1.3:8096 is working, http://10.12.1.2:11180 is not working (tv requesting those 3 files, screen black, no loading indicator)

**Comment by DpunktKpunkt** [comment]
Same behavior with webOS TV Emulator 4.00 and jellyfin 1.0.1 ipk.
Server ip address http://10.12.1.2:11180 (nginx reverse proxy) with black screen in emulator, server address http://10.12.1.3:8096 shows login screen for user.

**Comment by DpunktKpunkt** [comment]
I finally got the solution!

Wireshark with emulator showed that nginx added directive "X-Frame-Options: SAMEORIGIN". This won't work for proxied jellyfin.

Either overwrite this directive for server entry with ```add_header Access-Control-Allow-Origin "*" always;``` or something more restrictive for the specific network environment.

**Comment by mdPlusPlus** [comment]
Is it `add_header Access-Control-Allow-Origin "*" always;` or `proxy_set_header Access-Control-Allow-Origin "*" always;` and does it need to go into the `/` or the `/socket` block?

**Comment by DpunktKpunkt** [comment]
I added it to my server section. This is the full jellyfin config for nginx working as reverse proxy.
```
server {
        listen 80;
        listen [::]:80;
        server_name jellyfin.redacted.tld;

        location /.well-known/acme-challenge {
            alias /webroot/.well-known/acme-challenge;
            break;
        }

        location / {
            return 301 https://$host$request_uri;
        }
}


server {
        listen 443 ssl http2;
        listen [::]:443 ssl http2;
        server_name jellyfin.redacted.tld;

        set $jellyfin 10.17.0.4;

        include snippets/ssl-jellyfin.redacted.td.conf;
        include snippets/ssl-params-jellyfin.conf;

        root /webroot/jail;

        add_header Access-Control-Allow-Origin "*" always;

        location = / {
            return 302 https://$host/web/;
        }

        location / {
            # Proxy main Jellyfin traffic
            proxy_pass http://$jellyfin:8096;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Protocol $scheme;
            proxy_set_header X-Forwarded-Host $http_host;
            proxy_hide_header X-Frame-Options;

            # Disable buffering when the nginx proxy gets very resource heavy upon streaming
            proxy_buffering off;
        }

        # location block for /web - This is purely for aesthetics so /web/#!/ works instead of having to go to /web/index.html/#!/
        location = /web/ {
            # Proxy main Jellyfin traffic
            proxy_pass http://$jellyfin:8096/web/index.html;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Protocol $scheme;
            proxy_set_header X-Forwarded-Host $http_host;
            proxy_hide_header X-Frame-Options;
        }

        location /socket {
            # Proxy Jellyfin Websockets traffic
            proxy_pass http://$jellyfin:8096;
            proxy_http_version 1.1;
            proxy_read_timeout 86400s;
            proxy_send_timeout 86400s;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Protocol $scheme;
            proxy_set_header X-Forwarded-Host $http_host;
            proxy_hide_header X-Frame-Options;
        }
}
```

**Comment by mdPlusPlus** [comment]
Hm, unfortunately that does not seem to work on my setup. I've also been experimenting with `add_header Content-Security-Policy "frame-ancestors *";` and `add_header X-Frame-Options "ALLOW-FROM *";`, but somehow I haven't gotten it to work.   
I'll keep trying and give an update when I got it to work.

**Comment by DpunktKpunkt** [comment]
Would you mind sharing your config file? Maybe someone will notice something which leads to your error.

**Comment by mdPlusPlus** [comment]
This is the current state of the config. Unfortunately the TV is not at my place, so iterating on the config and testing it is a bit cumbersome. I might temporarily set up remote SSH access to my Jellyfin server, so I can better test this when I'm in front of the TV.

```
# configuration file /etc/nginx/conf.d/jellyfin.conf:
## Adds a trailing slash, why?
#server {
#       server_name jellyfin.example.com;
#       server_tokens off;
#       listen 80;
#
#       return 302 https://jellyfin.example.com:64889\$request_uri;
#}

server {
        server_name jellyfin.example.com;
        server_tokens off;
        listen 64889 ssl;
        http2 on;

        # <TLS config>
        ssl_certificate         /etc/letsencrypt/live/jellyfin.example.com/fullchain.pem;
        ssl_certificate_key     /etc/letsencrypt/live/jellyfin.example.com/privkey.pem;
        include conf.d/ssl_cipherlist.eu.conf;
        # </TLS config>

        ### experimental stuff for webOS here
        #add_header X-Frame-Options "ALLOW-FROM *";
        add_header Content-Security-Policy "frame-ancestors *";
        add_header Access-Control-Allow-Origin "*" always;
        ###

        access_log  /var/log/nginx/jellyfin-access.log;
        error_log   /var/log/nginx/jellyfin-error.log;

        set $jellyfin 1.2.3.4;

        location / {
                # Proxy main Jellyfin traffic
                proxy_pass http://$jellyfin:8096;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Forwarded-Protocol $scheme;
                proxy_set_header X-Forwarded-Host $http_host;

                # LG webOS fix?
                proxy_hide_header X-Frame-Options;

                # Disable buffering when the nginx proxy gets very resource heavy upon streaming
                proxy_buffering off;
        }

        location /socket {
                # Proxy Jellyfin Websockets traffic
                proxy_pass http://$jellyfin:8096;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Forwarded-Protocol $scheme;
                proxy_set_header X-Forwarded-Host $http_host;

                # LG webOS fix?
                proxy_hide_header X-Frame-Options;
        }
}

# configuration file /etc/nginx/conf.d/ssl_cipherlist.eu.conf:
#ssl_protocols TLSv1.3;                         # Requires nginx >= 1.13.0 else use TLSv1.2
ssl_protocols TLSv1.3 TLSv1.2;                  # Enable TLS 1.2 for Jellyfin on Kodi 18 and Fire TV sticks!
ssl_prefer_server_ciphers on;
ssl_dhparam /etc/ssl/certs/dhparam_4096.pem;    # openssl dhparam -out /etc/ssl/certs/dhparam_4096.pem 4096
ssl_ciphers EECDH+AESGCM:EDH+AESGCM;
ssl_ecdh_curve secp384r1;                       # Requires nginx >= 1.1.0
ssl_session_timeout  10m;
ssl_session_cache shared:SSL:10m;
ssl_session_tickets off;                        # Requires nginx >= 1.5.9
ssl_stapling on;                                # Requires nginx >= 1.3.7
ssl_stapling_verify on;                         # Requires nginx => 1.3.7
resolver 9.9.9.9 8.8.8.8 valid=300s;
resolver_timeout 5s;

## Disable preloading HSTS for now.  You can use the commented out header line that includes
## the "preload" directive if you understand the implications.
#add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; preload";
## Disable HSTS completely for now.
#add_header Strict-Transport-Security "max-age=63072000; includeSubdomains";

# add_header X-Frame-Options DENY;              # LG webOS fix?
add_header X-Content-Type-Options nosniff;
add_header X-XSS-Protection "1; mode=block";
```

**Comment by DpunktKpunkt** [comment]
Did you update your certificate list as mentioned [here](#issue-1104815758)? Afair my TV had problems with LE certificate so I switched to ZeroSSL for my jellyfin URL.

**Comment by mdPlusPlus** [comment]
https://webostv.developer.lge.com/develop/specifications/tls

>The Let's Encrypt certificate, which uses ISRG Root X1 as root, is supported from webOS TV 5.0. However, on webOS TV 3.X and 4.X, if the software update is properly performed, it is supported.

The TV has webOS TV 23 (?), so I doubt that's an issue, but thanks for the suggestion.

**Comment by mdPlusPlus** [comment]
The posted config actually works. I assume there was some kind of cache that had to be flushed and that is why it didn't work immediately, but a few days after setting the aboce config the app actually works as expected.
