### ISSUE TITLE
Jellyfin app doesn't appear in the LG Content Store

### ISSUE THREAD

**Issue by Nicolas-Lavinicki** [jellyfin/jellyfin-webos#89]
I couldn't find the app in the store, my TV model is UJ6585 and the version is 06.00.04 
Are there any limitations/differences between countries? I'm from Brazil. Can someone explain to me why the Jellyfin app doesn't appear in the LG Content Store?
![IMG_20220709_081146.jpg](https://user-images.githubusercontent.com/100033919/178104537-a010c8a3-eff4-46a8-ae4e-b7048bcebad6.jpg)
![IMG_20220709_081027.jpg](https://user-images.githubusercontent.com/100033919/178104543-dddd10d8-343f-45e8-93b0-f1ff71c08337.jpg)

**Comment by DrConflict** [comment]
You are not on WebOS 6+. This has been explained in detail on the announcement post, no clue why a whole github issue had to be created for this. WebOS 5 and lower will follow soon.

**Comment by Nicolas-Lavinicki** [comment]
> You are not on WebOS 6+. This has been explained in detail on the announcement post, no clue why a whole github issue had to be created for this. WebOS 5 and lower will follow soon.

Thanks for answering! I thought version "06.00.04" meant WebOS 6. It was a misunderstanding.

**Comment by arthurEspooner** [comment]
stick with plex. these kids are a joke.
