### ISSUE TITLE
Low resolution of UI elements

### ISSUE THREAD

**Issue by DrConflict** [jellyfin/jellyfin-webos#90]
Certain UI elements like the playback info window and media thumbnails are shown in low resolutions. It's very noticeable on 4K screens. 

Edit: After closer inspection it seems to be the complete UI that's in a relatively low resolution and not just certain elements.

LG C1
WebOS 6.3.1 (03.33.11)
JF Server 10.8.1
JF WebOS 1.1.0

**Comment by anthonylavado** [comment]
I think I know the cause for this, and it's something I have to follow up on.

The tl;dr is that you have to choose what size UI you're shipping for, and then LG makes decisions with that for channel display. If/when you were sideloaded, was the UI fine?

**Comment by DrConflict** [comment]
I'm not sure. But since I only seemed to notice it once the official release dropped I'm guessing yes. I can run some tests later today and sideload 1.1.0 if you want though. I'll keep you updated once I confirm things.

**Comment by DrConflict** [comment]
I can confirm that sideloading 1.1.0 fixes the issue. It's only the package from the LG content store that has the low resolution.

**Comment by anthonylavado** [comment]
> I can confirm that sideloading 1.1.0 fixes the issue. It's only the package from the LG content store that has the low resolution.

Got it. Thanks. I know the fix.
