### ISSUE TITLE
UI and Video Resolution

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin-webos#93]
## Issue
On UHD model TVs (2160P), the UI elements, including startup logo, may appear blurry.

## Cause
When submitting an app to LG, you have the option to declare the "Graphics Display Resolution".

LG has public documentation on "[Supported App Resolution](https://webostv.developer.lge.com/discover/specifications/supported-app-resolution/)".

On Full HD (FHD) models, LG states that the UI displays at 720P, while video playback will run at 1080P.

On Ultra HD (UHD) models, the UI displays at 1080P, while video playback runs at 2160P.

During submission, LG recommends submitting two versions of the app. One should be laid out for FHD models, and one should be for UHD models. You can submit a single version of it, but the TV will have to scale any graphical resources to fit the required size.

When I submitted the app, I chose the FHD resolution believing it was the minimum supported resolution, assuming the app would run natively at the highest possible resolution. I chose the setting without knowing the consequences this would have on UI display (and possibly video playback).

Some initial reports have indicated that the UI elements are blurry in certain cases on display sets, and that if the app is manually installed via developer mode, the UI is correct (see #90). The dev install "works" because we do not declare a resolution in appinfo.json, so it just runs at the higher setting by default.

## Fix
Upon the next submission to LG, I will upload the file and declare the resolution as UHD. This will allow the UI to be at the higher resolution where supported, and the TV will scale down for lower resolution sets. Since there are not many graphical elements packaged in the app, there is no need to build two versions. The Jellyfin web interface already accounts for this when it is running.

**Comment by tiagogaspar8** [comment]
Hi,

Is there a estimate timeframe when submitting the app with this fix? Thanks!

**Comment by tobimori** [comment]
Any update on when this might happen?

**Comment by anthonylavado** [comment]
Currently awaiting LG's review.

**Comment by anthonylavado** [comment]
Update - small setback from QA at LG. Making the necessary fix and submitting again later today.

**Comment by tiagogaspar8** [comment]
Thanks for the update!

**Comment by mr-vercetti** [comment]
Hello,
Is it known when this will be fixed? I have the current webOS and Jellyfin but the UI continues to be blurry.

**Comment by anthonylavado** [comment]
The update that adds compatibility for webOS 5 has been released, and I also made the setting change on the portal to have the correct resolution set for the app.

Could you update to version 1.1.2 and let me know if this still persists? Thanks!
