### ISSUE TITLE
Subtitle Sync Breaks on Resume

### ISSUE THREAD

**Issue by nnhimes** [jellyfin/jellyfin-webos#95]
When pausing and exiting a stream at _X_ minutes, then coming back to it later, I found a bug where sometimes the subtitles will be offset by _+X_ minutes.

Ex) Pause at 5:00 minutes, on resume subtitles are synced to the 10:00 mark. Rewinding back to the start would play the subtitles at 5:00.

**Comment by Simonh2o** [comment]
Also having this issue, it's rarely synced for me. Doesn't seem to matter if you pause/resume/enable cc.

**Comment by anthonylavado** [comment]
We are aware of a possible issue when using embedded subtitles.

Could you both provide some extra info on the media, and the subtitles? This should be available by looking at this listing for any item, then clicking the three dot menu and choosing "Media Info".

**Comment by nnhimes** [comment]
All the ones I've had the problem with so far are HEVC Main 10 (both 1080p SDR and 4k HDR) with SUBRIP subtitles

**Comment by Simonh2o** [comment]
Exactly as @nnhimes describes. Both 1080p SDR and 4K HDR with SUBRIP subtitles. x264/high. It's fine on web.

**Comment by nnhimes** [comment]
Fixed by updating Jellyfin to latest
